'use client';
import { useEffect, useState } from 'react';
import { ExternalLink, Plus, X } from 'lucide-react';
import styles from './MessagesAccounts.module.css';

interface Account { id: string; label: string; address?: string }
const userScopes = ['channels:history', 'groups:history', 'im:history', 'mpim:history', 'channels:read', 'groups:read', 'im:read', 'mpim:read', 'users:read', 'chat:write', 'files:write', 'files:read', 'reactions:read', 'channels:write', 'groups:write', 'im:write', 'mpim:write'];
export function MessagesAccounts() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [open, setOpen] = useState(false); const [token, setToken] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { const controller = new AbortController(); void fetch('/api/connectors/slack/messages-accounts', { signal: controller.signal, cache: 'no-store' }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load Slack accounts.'); setAccounts(data.accounts); }).catch(err => { if (err.name !== 'AbortError') setError('Could not load Slack accounts. Try again.'); }); return () => controller.abort(); }, []);
  const connect = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); setNotice(''); try { const response = await fetch('/api/connectors/slack/messages-accounts', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token: token.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Slack could not connect. Try again.'); setToken(''); setAccounts(previous => [...previous.filter(account => account.id !== data.account.id), data.account]); if (data.missingScopes?.length) setNotice(`${data.account.label} needs setup. Add these User Token Scopes and reinstall the Slack app: ${data.missingScopes.join(', ')}.`); else { setNotice(`${data.account.label} is connected to Messages.`); setOpen(false); } } catch { setError('Slack could not connect. Check the User OAuth Token and try again.'); } finally { setBusy(false); } };
  return <section className={styles.section} aria-label="Slack Messages accounts"><h3>Messages accounts</h3><p>Connect each workspace with your Slack user account to include your DMs, groups and channels.</p>{accounts.length > 0 && <ul>{accounts.map(account => <li key={account.id}><strong>{account.label}</strong>{account.address && <span>{account.address}</span>}</li>)}</ul>}{error && <p role="alert" className={styles.error}>{error}</p>}{notice && <p role="status">{notice}</p>}{!open ? <button type="button" onClick={() => setOpen(true)}><Plus size={16} />Add Messages account</button> : <form onSubmit={connect}><div className={styles.top}><h4>Add a workspace</h4><button type="button" aria-label="Cancel adding Messages account" onClick={() => { setOpen(false); setToken(''); }}><X size={18} /></button></div><ol><li>Open your app in <a href="https://api.slack.com/apps" target="_blank" rel="noreferrer">Slack Apps<ExternalLink size={12} /></a>.</li><li>In OAuth &amp; Permissions, add the User Token Scopes below, then reinstall the app to your workspace.</li><li>Copy the User OAuth Token into this field.</li></ol><details><summary>Required User Token Scopes</summary><p className={styles.scopes}>{userScopes.join(', ')}</p></details><label>User OAuth Token<input type="password" value={token} onChange={event => setToken(event.target.value)} autoComplete="off" spellCheck={false} placeholder="xoxp-" required pattern="xoxp-.*" /></label><button type="submit" disabled={busy || !token.trim()}>{busy ? 'Connecting...' : 'Connect workspace'}</button></form>}</section>;
}
