'use client';
import { useEffect, useState } from 'react';
import { File, Search, X } from 'lucide-react';
import type { Attachment, Provider } from './types';
import { request } from './client';
import styles from './composer.module.css';
interface DriveFile { id: string; name: string; mimeType: string; size?: string; modifiedTime?: string; webViewLink?: string }
export function DrivePicker({ provider, targetProvider, targetAccount, onFile, onLink, onClose }: { provider: Provider; targetProvider: string; targetAccount: string; onFile: (attachment: Attachment) => void; onLink: (name: string, link: string) => void; onClose: () => void }) {
  const [account, setAccount] = useState(provider.accounts[0]?.id || ''); const [query, setQuery] = useState(''); const [files, setFiles] = useState<DriveFile[]>([]); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  useEffect(() => { let active = true; const timer = setTimeout(() => { setLoading(true); void request<{ files: DriveFile[] }>(`/drive?account=${encodeURIComponent(account)}&q=${encodeURIComponent(query)}`).then(result => { if (active) { setFiles(result.files); setError(''); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); }, query ? 250 : 0); return () => { active = false; clearTimeout(timer); }; }, [account, query]);
  const select = async (file: DriveFile) => { setBusy(file.id); setError(''); try { const result = await request<{ attachment?: Attachment; link?: string; name?: string }>('/drive', { account, fileId: file.id, targetProvider, targetAccount }); if (result.attachment) onFile(result.attachment); else if (result.link) onLink(result.name || file.name, result.link); onClose(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not attach the Drive file.'); } finally { setBusy(''); } };
  return <div className={styles.backdrop} onClick={onClose}><section className={styles.picker} role="dialog" aria-modal="true" aria-label="Google Drive" onClick={event => event.stopPropagation()}><header><h2>Google Drive</h2><button type="button" aria-label="Close Google Drive" onClick={onClose}><X size={20} /></button></header>{provider.accounts.length > 1 && <label>Account<select value={account} onChange={event => setAccount(event.target.value)}>{provider.accounts.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}<div className={styles.driveSearch}><Search size={17} /><input autoFocus aria-label="Search Google Drive" placeholder="Search files" value={query} onChange={event => setQuery(event.target.value)} /></div>{error && <p role="alert">{error}</p>}<div className={styles.driveFiles}>{loading ? <p>Loading files…</p> : !files.length ? <p>No files found.</p> : files.map(file => <button key={file.id} type="button" disabled={!!busy} onClick={() => void select(file)}><File size={19} /><span><strong>{file.name}</strong><small>{busy === file.id ? 'Attaching…' : Number(file.size) > 25 * 1024 * 1024 ? 'Attach as a link' : file.size ? `${Math.ceil(Number(file.size) / 1024)} KB` : 'Google Drive'}</small></span></button>)}</div></section></div>;
}
