import type { Filter, Provider } from './types';
import { categories } from './client';
import { ProviderBadge } from './ProviderBadge';
import styles from './messages.module.css';

export function FilterControls({ filter, onChange, providers, agents = true, labels = [] }: { filter: Filter; onChange: (filter: Filter) => void; providers: Provider[]; agents?: boolean; labels?: string[] }) {
  const update = (key: keyof Filter, value: unknown) => { const next = { ...filter, [key]: value }; if (value === undefined || value === '' || (Array.isArray(value) && !value.length)) delete next[key]; onChange(next); };
  const toggleList = (key: 'providers' | 'accounts' | 'categories' | 'severity' | 'labels', value: string) => { const values = (filter[key] || []) as string[]; update(key, values.includes(value) ? values.filter(item => item !== value) : [...values, value]); };
  const date = (days: number) => { const start = new Date(); start.setHours(0, 0, 0, 0); if (days === 7) start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); else if (days === 30) start.setDate(1); update('dateFrom', start.toISOString()); };
  return <div className={styles.filterControls} onFocusCapture={event => { const target = event.target as HTMLElement; const container = event.currentTarget; const overflow = target.getBoundingClientRect().bottom - container.getBoundingClientRect().bottom + 12; if (overflow > 0) container.scrollTop += overflow; }}>
    <fieldset><legend>Status</legend><div className={styles.chips}>{([['unread', 'Unread'], ['actionable', 'Needs me'], ['starred', 'Starred'], ['archived', 'Archived']] as const).map(([key, label]) => <button key={key} type="button" aria-pressed={!!filter[key]} onClick={() => update(key, filter[key] ? undefined : true)}>{label}</button>)}</div></fieldset>
    <fieldset><legend>Attachments</legend><div className={styles.chips}><button type="button" aria-pressed={!!filter.hasAttachments} onClick={() => update('hasAttachments', filter.hasAttachments ? undefined : true)}>Any</button>{([['image', 'Images'], ['audio', 'Audio'], ['file', 'Files']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={filter.attachmentKind === value} onClick={() => update('attachmentKind', filter.attachmentKind === value ? undefined : value)}>{label}</button>)}</div></fieldset>
    <fieldset><legend>Provider</legend><div className={styles.chips}>{providers.map(provider => <button type="button" key={provider.id} aria-pressed={filter.providers?.includes(provider.id) || false} onClick={() => toggleList('providers', provider.id)}><ProviderBadge provider={provider} /></button>)}</div></fieldset>
    {providers.some(provider => provider.accounts.length > 1) && <fieldset><legend>Account</legend><div className={styles.chips}>{providers.flatMap(provider => provider.accounts.map(account => <button key={`${provider.id}/${account.id}`} type="button" aria-pressed={filter.accounts?.includes(account.id) || false} onClick={() => toggleList('accounts', account.id)}>{account.label}</button>))}</div></fieldset>}
    <label>From<input placeholder="Name or address" value={filter.from || ''} onChange={event => update('from', event.target.value)} /></label>
    <fieldset><legend>Date</legend><div className={styles.chips}><button type="button" onClick={() => date(1)}>Today</button><button type="button" onClick={() => date(7)}>This week</button><button type="button" onClick={() => date(30)}>This month</button></div><div className={styles.dateRange}><label>From date<input type="date" value={filter.dateFrom?.slice(0, 10) || ''} onChange={event => update('dateFrom', event.target.value ? `${event.target.value}T00:00:00.000Z` : undefined)} /></label><label>To date<input type="date" value={filter.dateTo?.slice(0, 10) || ''} onChange={event => update('dateTo', event.target.value ? `${event.target.value}T23:59:59.999Z` : undefined)} /></label></div></fieldset>
    {labels.length > 0 && <fieldset><legend>Labels</legend><div className={styles.chips}>{labels.map(label => <button key={label} type="button" aria-pressed={filter.labels?.includes(label) || false} onClick={() => toggleList('labels', label)}>{label}</button>)}</div></fieldset>}
    <fieldset><legend>Direction</legend><div className={styles.chips}>{(['in', 'out'] as const).map(value => <button key={value} type="button" aria-pressed={filter.direction === value} onClick={() => update('direction', filter.direction === value ? undefined : value)}>{value === 'in' ? 'Received' : 'Sent'}</button>)}</div></fieldset>
    {agents && <><fieldset><legend>Severity</legend><div className={styles.chips}>{(['info', 'warning', 'error'] as const).map(value => <button key={value} type="button" aria-pressed={filter.severity?.includes(value) || false} onClick={() => toggleList('severity', value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div></fieldset><fieldset><legend>Category</legend><div className={styles.chips}>{Object.entries(categories).map(([value, label]) => <button key={value} type="button" aria-pressed={filter.categories?.includes(value) || false} onClick={() => toggleList('categories', value)}>{label}</button>)}</div></fieldset></>}
  </div>;
}
