'use client';
import { useEffect, useRef, useState } from 'react';
import { ExternalLink, Image as ImageIcon, Reply, Forward, Users, Star } from 'lucide-react';
import type { Message, Provider } from './types';
import { MessageBody } from './MessageBody';
import { request, providerLabels } from './client';
import styles from './mail.module.css';

export type ReplyMode = 'reply' | 'reply-all' | 'forward';
export interface MailFields { address: string; cc: string; subject: string }
export function replyFields(message: Message, mode: ReplyMode): MailFields {
  if (mode === 'forward') return { address: '', cc: '', subject: /^fwd?:/i.test(message.subject || '') ? message.subject || '' : `Fwd: ${message.subject || ''}` };
  const otherRecipients = message.recipients.filter(person => !person.isMe && person.address && person.address !== message.sender.address);
  return { address: message.sender.address || '', cc: mode === 'reply-all' ? otherRecipients.map(person => person.address).join(', ') : '', subject: /^re:/i.test(message.subject || '') ? message.subject || '' : `Re: ${message.subject || ''}` };
}
export function MailComposerFields({ value, onChange, addressRequired = true }: { value: MailFields; onChange: (fields: MailFields) => void; addressRequired?: boolean }) {
  return <div className={styles.fields}><label>To<input aria-label="To" required={addressRequired} placeholder="name@example.com" value={value.address} onChange={event => onChange({ ...value, address: event.target.value })} /></label><label>Cc<input aria-label="Cc" placeholder="Optional" value={value.cc} onChange={event => onChange({ ...value, cc: event.target.value })} /></label><label>Subject<input aria-label="Subject" value={value.subject} onChange={event => onChange({ ...value, subject: event.target.value })} /></label></div>;
}
export function MailHtml({ message }: { message: Message }) {
  const [loadedImages, setLoadedImages] = useState(false); const [html, setHtml] = useState(''); const [height, setHeight] = useState(200); const [error, setError] = useState(''); const [links, setLinks] = useState<{ href: string; label: string }[]>([]); const frame = useRef<HTMLIFrameElement>(null);
  useEffect(() => { const controller = new AbortController(); setError(''); void fetch(`/api/messages/${encodeURIComponent(message.id)}/html${loadedImages ? '?images=1' : ''}`, { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error('Could not load this mail.'); return response.text(); }).then(text => { const doc = new DOMParser().parseFromString(text, 'text/html'); for (const blocked of doc.querySelectorAll('img[data-message-image]')) { if (!blocked.getAttribute('src')) { const label = doc.createElement('span'); label.textContent = 'Image blocked'; label.setAttribute('style', 'display:block;padding:12px;border:1px solid #d2c8b4;border-radius:6px;color:#687064;font-size:12px'); blocked.replaceWith(label); } } setHtml(doc.body.innerHTML); setLinks(Array.from(doc.querySelectorAll('a[href]')).filter(link => /^(https?:|mailto:)/i.test(link.getAttribute('href') || '')).map(link => ({ href: link.getAttribute('href')!, label: link.textContent?.trim() || link.getAttribute('href')! })).filter((link, index, all) => all.findIndex(item => item.href === link.href) === index)); }).catch(err => { if (!controller.signal.aborted) setError(err.message); }); return () => controller.abort(); }, [message.id, loadedImages]);
  useEffect(() => { if (!frame.current || !html) return; const target = frame.current;
    const measure = () => { const host = document.createElement('div'); host.style.cssText = `position:fixed;left:-10000px;top:0;visibility:hidden;width:${target.clientWidth}px;contain:layout;`; const shadow = host.attachShadow({ mode: 'closed' }); const content = document.createElement('div'); content.innerHTML = html; for (const image of content.querySelectorAll('img')) { image.removeAttribute('src'); image.style.maxWidth = '100%'; } const style = document.createElement('style'); style.textContent = 'div{font:14px/1.6 system-ui;overflow-wrap:anywhere} img{max-width:100%;height:auto} pre{white-space:pre-wrap;overflow-wrap:anywhere} table{max-width:100%;table-layout:fixed}'; shadow.append(style, content); document.body.append(host); setHeight(Math.max(80, Math.min(4000, host.getBoundingClientRect().height + 24))); host.remove(); };
    measure(); const observer = new ResizeObserver(measure); observer.observe(target); return () => observer.disconnect();
  }, [html]);
  if (error) return <p role="alert">{error}</p>;
  const documentHtml = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:8px 0;font:14px/1.6 system-ui;color:#18211b;overflow-wrap:anywhere}img{max-width:100%;height:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere}table{max-width:100%;table-layout:fixed}a{color:#31563f}</style></head><body>${html}</body></html>`;
  return <div className={styles.html}><iframe ref={frame} title={`Mail from ${message.sender.name}`} sandbox="" referrerPolicy="no-referrer" srcDoc={documentHtml} style={{ height }} />{!loadedImages && <button type="button" onClick={() => setLoadedImages(true)}><ImageIcon size={15} />Load images</button>}{links.length > 0 && <div className={styles.links} aria-label="Mail links">{links.map(link => <a key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">{link.label}<ExternalLink size={13} /></a>)}</div>}</div>;
}
export function MailMessage({ message, provider, onReply, onChanged }: { message: Message; provider?: Provider; onReply: (message: Message, mode: ReplyMode) => void; onChanged: () => void }) {
  const [labelNames, setLabelNames] = useState<Record<string, string>>({});
  useEffect(() => { if (provider?.capabilities.labels) void providerLabels(provider.id, message.account).then(labels => setLabelNames(Object.fromEntries(labels.map(label => [label.id, label.name])))).catch(() => {}); }, [provider?.id, provider?.capabilities.labels, message.account]);
  const [starred, setStarred] = useState(message.starred); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => setStarred(message.starred), [message.starred]);
  const changeStar = async () => { const previous = starred; setStarred(!previous); try { await request(`/${encodeURIComponent(message.id)}/state`, { starred: !previous }); onChanged(); } catch { setStarred(previous); setError(`Could not update on ${provider?.label || 'Gmail'}. Reverted.`); } };
  const readOnly = !!provider?.setupHint || provider?.health?.ok === false;
  return <div className={styles.mail}><header><div><p><span>From</span><strong>{message.sender.name}</strong>{message.sender.address && <small>{message.sender.address}</small>}</p><p><span>To</span>{message.recipients.map(person => person.address || person.name).join(', ') || 'You'}</p></div><button type="button" aria-label={starred ? 'Unstar' : 'Star'} aria-pressed={starred} disabled={readOnly} onClick={() => void changeStar()}><Star size={17} fill={starred ? 'currentColor' : 'none'} /></button></header>{message.bodyHtmlPath ? <MailHtml message={message} /> : <MessageBody text={message.bodyText} markdown={message.bodyMarkdown} />}{message.labels.length > 0 && <div className={styles.labels}>{message.labels.filter(label => !['INBOX', 'UNREAD', 'SENT'].includes(label)).map(label => <span key={label}>{labelNames[label] || label}</span>)}</div>}{provider?.capabilities.reply && <div className={styles.replyActions}><button type="button" disabled={readOnly} onClick={() => onReply(message, 'reply')}><Reply size={16} />Reply</button><button type="button" disabled={readOnly} onClick={() => onReply(message, 'reply-all')}><Users size={16} />Reply all</button><button type="button" disabled={readOnly} onClick={() => onReply(message, 'forward')}><Forward size={16} />Forward</button></div>}{error && <p className={styles.error} role="alert">{error}</p>}</div>;
}
