'use client';
import { useEffect, useRef, useState } from 'react';
import { Download, File as FileIcon, Image as ImageIcon, LoaderCircle, Minus, Pause, Play, Plus, X } from 'lucide-react';
import type { Attachment, Message } from './types';
import styles from './media.module.css';

export const attachmentUrl = (messageId: string, attachmentId: string, variant?: string) => `/api/messages/attachments/${encodeURIComponent(messageId)}/${encodeURIComponent(attachmentId)}${variant ? `?variant=${variant}` : ''}`;
export function mediaDuration(milliseconds: number | null | undefined) { const seconds = Math.max(0, Math.floor((milliseconds || 0) / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; }
function bytesLabel(bytes: number) { return bytes >= 1048576 ? `${(bytes / 1048576).toFixed(1)} MB` : bytes >= 1024 ? `${Math.round(bytes / 1024)} KB` : `${bytes} B`; }
export function AudioPlayer({ attachment, src }: { attachment: Attachment; src: string }) {
  const audio = useRef<HTMLAudioElement>(null); const [playing, setPlaying] = useState(false); const [position, setPosition] = useState(0); const [duration, setDuration] = useState((attachment.durationMs || 0) / 1000); const [speed, setSpeed] = useState(1); const [error, setError] = useState('');
  const toggle = async () => { if (!audio.current) return; if (playing) audio.current.pause(); else { try { await audio.current.play(); setError(''); } catch (err) { if (!(err instanceof DOMException && err.name === 'AbortError')) setError('Could not play this voice note.'); } } };
  return <div className={styles.audio} aria-label={`Voice note ${mediaDuration(duration * 1000)}`}><audio ref={audio} preload="metadata" src={src} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => setPlaying(false)} onTimeUpdate={() => setPosition(audio.current?.currentTime || 0)} onLoadedMetadata={() => { const measured = audio.current?.duration; if (measured && Number.isFinite(measured)) setDuration(measured); }} /><div className={styles.audioControls}><button type="button" aria-label={playing ? 'Pause voice note' : 'Play voice note'} onClick={() => void toggle()}>{playing ? <Pause size={19} /> : <Play size={19} />}</button><div><input type="range" aria-label="Audio position" min={0} max={duration || 1} step={0.1} value={Math.min(position, duration || 1)} onChange={event => { const value = Number(event.target.value); if (audio.current) audio.current.currentTime = value; setPosition(value); }} /><span>{mediaDuration(position * 1000)} / {mediaDuration(duration * 1000)}</span></div><select aria-label="Playback speed" value={speed} onChange={event => { const value = Number(event.target.value); setSpeed(value); if (audio.current) audio.current.playbackRate = value; }}><option value={1}>1x</option><option value={1.5}>1.5x</option><option value={2}>2x</option></select></div>{attachment.transcriptStatus === 'pending' && <p className={styles.transcriptStatus}>Transcribing</p>}{attachment.transcriptStatus === 'failed' && <p className={styles.transcriptStatus} title={attachment.transcriptError}>Transcript unavailable</p>}{attachment.transcript && <details open={attachment.transcript.length < 300}><summary>Transcript</summary><p>{attachment.transcript}</p></details>}{error && <p role="alert">{error}</p>}</div>;
}
function ImageViewer({ src, name, onClose }: { src: string; name: string; onClose: () => void }) {
  const [scale, setScale] = useState(1); const pinch = useRef<{ distance: number; scale: number } | null>(null); const close = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; close.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', escape); return () => { document.removeEventListener('keydown', escape); previous?.focus(); }; }, [onClose]);
  return <div className={styles.viewer} role="dialog" aria-modal="true" aria-label={name}><header><span>{name}</span><button type="button" aria-label="Zoom out" onClick={() => setScale(value => Math.max(1, value - .5))}><Minus size={18} /></button><button type="button" aria-label="Zoom in" onClick={() => setScale(value => Math.min(5, value + .5))}><Plus size={18} /></button><button type="button" ref={close} aria-label="Close photo" onClick={onClose}><X size={22} /></button></header><div className={styles.viewerCanvas} onTouchStart={event => { if (event.touches.length === 2) pinch.current = { distance: Math.hypot(event.touches[0].clientX - event.touches[1].clientX, event.touches[0].clientY - event.touches[1].clientY), scale }; }} onTouchMove={event => { if (event.touches.length === 2 && pinch.current) setScale(Math.max(1, Math.min(5, pinch.current.scale * Math.hypot(event.touches[0].clientX - event.touches[1].clientX, event.touches[0].clientY - event.touches[1].clientY) / pinch.current.distance))); }} onTouchEnd={() => { pinch.current = null; }}><img src={src} alt={name} style={{ transform: `scale(${scale})` }} onDoubleClick={() => setScale(value => value === 1 ? 2 : 1)} /></div></div>;
}
export function MessageMedia({ message, onRefresh, onNotice }: { message: Message; onRefresh: () => void; onNotice: (message: string) => void }) {
  const [viewer, setViewer] = useState<Attachment | null>(null); const [downloading, setDownloading] = useState<string | null>(null); const mounted = useRef(true); useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const open = async (attachment: Attachment) => { setDownloading(attachment.id); try { const url = attachmentUrl(message.id, attachment.id); let response = await fetch(url); for (let retry = 0; response.status === 202 && retry < 10; retry++) { await new Promise(resolve => setTimeout(resolve, 1500)); if (!mounted.current) return; response = await fetch(url); } if (response.status === 202) throw new Error('Attachment is still downloading. Try again shortly.'); if (!response.ok) throw new Error('Could not download this attachment.'); if (attachment.kind === 'image') { setViewer(attachment); onRefresh(); } else { const blob = await response.blob(); const objectUrl = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = objectUrl; link.download = attachment.name; link.click(); setTimeout(() => URL.revokeObjectURL(objectUrl), 30000); onRefresh(); } } catch (err) { onNotice(err instanceof Error ? err.message : 'Could not download this attachment.'); } finally { if (mounted.current) setDownloading(null); } };
  if (!message.attachments.length) return null;
  return <div className={styles.media}>{message.attachments.map(attachment => attachment.kind === 'audio' && attachment.path ? <AudioPlayer key={attachment.id} attachment={attachment} src={attachmentUrl(message.id, attachment.id, 'playback')} /> : attachment.kind === 'image' ? <button className={styles.photo} type="button" key={attachment.id} aria-label={`Open photo ${attachment.name}`} disabled={downloading === attachment.id} onClick={() => void open(attachment)}>{attachment.path ? <img src={attachmentUrl(message.id, attachment.id, 'thumbnail')} alt={attachment.name} loading="lazy" /> : <span><ImageIcon size={25} />Photo</span>}{downloading === attachment.id && <LoaderCircle size={18} />}</button> : <button type="button" key={attachment.id} className={styles.file} disabled={downloading === attachment.id} onClick={() => void open(attachment)}><FileIcon size={22} /><span><strong>{attachment.name}</strong><small>{bytesLabel(attachment.size)}</small></span>{downloading === attachment.id ? <LoaderCircle size={17} /> : <Download size={17} />}</button>)}{viewer && <ImageViewer src={attachmentUrl(message.id, viewer.id)} name={viewer.name} onClose={() => setViewer(null)} />}</div>;
}
