'use client';
import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowUp, Bold, Camera, Code, File as FileIcon, Image as ImageIcon, Italic, Link, Mic, Paperclip, Square, X } from 'lucide-react';
import { ComposerAttachmentChips, SharedComposerFileInput, SharedComposerInput, readComposerUpload } from '../../../packages/claude-chat/src/SharedComposer';
import type { ComposerAttachment } from '../../../packages/claude-chat/src/SharedComposer';
import type { Attachment, Provider } from './types';
import { AudioPlayer, mediaDuration } from './MessageMedia';
import { DrivePicker } from './DrivePicker';
import { request } from './client';
import styles from './composer.module.css';
export type ComposerMedia = Attachment & { asVoiceNote?: boolean };
type Pending = ComposerAttachment & { attachment?: ComposerMedia; voice?: boolean };
export interface SendDraft { markdown: string; attachments: ComposerMedia[] }
export function MessageComposer({ provider, account, providers, draft, setDraft, onSend, sending, disabled, children, textareaRef }: { provider: Provider; account: string; providers: Provider[]; draft: string; setDraft: (draft: string) => void; onSend: (draft: SendDraft) => Promise<boolean>; sending: boolean; disabled: boolean; children?: ReactNode; textareaRef?: React.RefObject<HTMLTextAreaElement> }) {
  const localInput = useRef<HTMLTextAreaElement>(null); const input = textareaRef || localInput; const files = useRef<HTMLInputElement>(null); const photos = useRef<HTMLInputElement>(null); const camera = useRef<HTMLInputElement>(null);
  const [pending, setPending] = useState<Pending[]>([]); const [attachMenu, setAttachMenu] = useState(false); const [drive, setDrive] = useState(false); const [driveAvailable, setDriveAvailable] = useState(false); const [error, setError] = useState(''); const [recording, setRecording] = useState(false); const [elapsed, setElapsed] = useState(0); const [dragOver, setDragOver] = useState(false);
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const recordStarted = useRef(0); const recordGeneration = useRef(0); const cancelled = useRef(false); const pointerStart = useRef<number | null>(null); const touchRecord = useRef(false); const pendingRef = useRef(pending); pendingRef.current = pending;
  const driveProvider = driveAvailable ? providers.find(item => item.id === 'google') : undefined;
  useEffect(() => { let live = true; if (providers.some(item => item.id === 'google')) void request<{ accounts?: unknown[] }>('/drive').then(result => { if (live) setDriveAvailable(!!result.accounts?.length); }).catch(() => { if (live) setDriveAvailable(false); }); return () => { live = false; }; }, [providers]);
  useEffect(() => { if (!input.current) return; input.current.style.height = 'auto'; input.current.style.height = `${Math.min(input.current.scrollHeight, 144)}px`; }, [draft, input]);
  useEffect(() => () => { recordGeneration.current++; cancelled.current = true; if (recorder.current?.state === 'recording') recorder.current.stop(); stream.current?.getTracks().forEach(track => track.stop()); pendingRef.current.forEach(item => { if (item.previewUrl) URL.revokeObjectURL(item.previewUrl); }); }, []);
  useEffect(() => { if (!recording) return; const timer = setInterval(() => setElapsed(Date.now() - recordStarted.current), 100); return () => clearInterval(timer); }, [recording]);
  const upload = async (file: File, voice = false) => { if (file.size > 25 * 1024 * 1024) { setError('Files must be 25 MB or smaller.'); return; } const id = crypto.randomUUID(); const previewUrl = file.type.startsWith('image/') || voice ? URL.createObjectURL(file) : null; setPending(current => [...current, { id, name: file.name || 'pasted-image.png', path: null, uploading: true, error: null, previewUrl, voice }]); try { const bytes = await readComposerUpload(file); const result = await request<{ attachment: Attachment }>('/attachments', { provider: provider.id, account, ...bytes }); setPending(current => current.map(item => item.id === id ? { ...item, path: result.attachment.path, uploading: false, attachment: { ...result.attachment, asVoiceNote: voice } } : item)); } catch (err) { setPending(current => current.map(item => item.id === id ? { ...item, uploading: false, error: err instanceof Error ? err.message : 'Could not attach file.' } : item)); } };
  const acceptFiles = (items: File[]) => { if (disabled || !provider.capabilities.attachments) return; setAttachMenu(false); items.forEach(file => void upload(file)); };
  const remove = (id: string) => setPending(current => { const item = current.find(item => item.id === id); if (item?.previewUrl) URL.revokeObjectURL(item.previewUrl); return current.filter(item => item.id !== id); });
  const addDriveFile = (attachment: Attachment) => setPending(current => [...current, { id: attachment.id, name: attachment.name, path: attachment.path, uploading: false, error: null, previewUrl: null, attachment }]);
  const format = (before: string, after = before) => { if (!input.current) return; const start = input.current.selectionStart, end = input.current.selectionEnd; setDraft(`${draft.slice(0, start)}${before}${draft.slice(start, end)}${after}${draft.slice(end)}`); requestAnimationFrame(() => { input.current?.focus(); input.current?.setSelectionRange(start + before.length, end + before.length); }); };
  const stopRecording = (cancel = false) => { cancelled.current = cancelled.current || cancel; recordGeneration.current++; if (recorder.current?.state === 'recording') recorder.current.stop(); else stream.current?.getTracks().forEach(track => track.stop()); setRecording(false); pointerStart.current = null; };
  const startRecording = async () => { if (disabled || !provider.capabilities.audioSend || recording) return; const generation = ++recordGeneration.current; setError(''); cancelled.current = false; try { const capture = await navigator.mediaDevices.getUserMedia({ audio: true }); if (generation !== recordGeneration.current) { capture.getTracks().forEach(track => track.stop()); return; } stream.current = capture; const mime = ['audio/webm;codecs=opus', 'audio/mp4', 'audio/webm'].find(value => MediaRecorder.isTypeSupported(value)) || ''; const instance = new MediaRecorder(capture, mime ? { mimeType: mime } : undefined); recorder.current = instance; const chunks: Blob[] = []; instance.ondataavailable = event => { if (event.data.size) chunks.push(event.data); }; instance.onstop = () => { capture.getTracks().forEach(track => track.stop()); stream.current = null; if (cancelled.current || !chunks.length) return; const type = instance.mimeType || mime || 'audio/webm'; const blob = new Blob(chunks, { type }); const extension = type.includes('mp4') ? 'm4a' : 'webm'; void upload(new globalThis.File([blob], `voice-note.${extension}`, { type: type.split(';')[0] }), true); }; instance.start(100); recordStarted.current = Date.now(); setElapsed(0); setRecording(true); } catch (err) { setError(err instanceof Error ? err.message : 'Microphone is unavailable.'); setRecording(false); } };
  const nativeCamera = async () => { setAttachMenu(false); const cap = (window as unknown as { Capacitor?: { isNativePlatform?: () => boolean; Plugins?: { Camera?: { getPhoto: (options: unknown) => Promise<{ webPath?: string }> } } } }).Capacitor; if (cap?.isNativePlatform?.() && cap.Plugins?.Camera?.getPhoto) { try { const photo = await cap.Plugins.Camera.getPhoto({ source: 'CAMERA', resultType: 'uri', quality: 90 }); if (photo.webPath) { const blob = await fetch(photo.webPath).then(response => response.blob()); await upload(new globalThis.File([blob], 'camera-photo.jpg', { type: blob.type || 'image/jpeg' })); } } catch (err) { setError(err instanceof Error ? err.message : 'Could not open the camera.'); } } else camera.current?.click(); };
  const submit = async () => { const ready = pending.flatMap(item => item.attachment ? [item.attachment] : []); if (disabled || sending || pending.some(item => item.uploading || item.error) || (!draft.trim() && !ready.length)) return; if (await onSend({ markdown: draft, attachments: ready })) { pending.forEach(item => { if (item.previewUrl) URL.revokeObjectURL(item.previewUrl); }); setPending([]); } };
  const voicePreview = pending.find(item => item.voice && item.attachment && item.previewUrl);
  return <form data-messages-composer className={`${styles.composer} ${dragOver ? styles.dragOver : ''}`} onSubmit={event => { event.preventDefault(); void submit(); }} onDragOver={event => { if (provider.capabilities.attachments && !disabled) { event.preventDefault(); setDragOver(true); } }} onDragLeave={() => setDragOver(false)} onDrop={event => { event.preventDefault(); setDragOver(false); acceptFiles(Array.from(event.dataTransfer.files)); }}>{children}{error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" aria-label="Dismiss composer error" onClick={() => setError('')}><X size={16} /></button></div>}<ComposerAttachmentChips attachments={pending.filter(item => !item.voice || !item.attachment)} onRemove={remove} classNames={{ list: styles.chips, chip: styles.chip, thumb: styles.thumb, name: styles.chipName, remove: styles.remove, error: styles.failed, spinner: styles.spinner }} />{voicePreview && <div className={styles.voicePreview}><AudioPlayer attachment={voicePreview.attachment!} src={voicePreview.previewUrl!} /><div><button type="button" onClick={() => remove(voicePreview.id)}>Cancel</button><button type="button" disabled={sending} onClick={() => void submit()}>Send voice note</button></div></div>}
    {provider.capabilities.markdown && <div className={styles.toolbar}><button type="button" aria-label="Bold" onClick={() => format('**')}><Bold size={16} /></button><button type="button" aria-label="Italic" onClick={() => format('*')}><Italic size={16} /></button><button type="button" aria-label="Inline code" onClick={() => format('`')}><Code size={16} /></button>{provider.capabilities.code && <button type="button" aria-label="Code block" onClick={() => format('```\n', '\n```')}>Code block</button>}<button type="button" aria-label="Insert link" onClick={() => format('[', '](https://)')}><Link size={16} /></button></div>}
    {recording ? <div className={styles.recording}><i /><span>Recording {mediaDuration(elapsed)}</span><small>Release to stop, slide to cancel</small><button type="button" aria-label="Stop recording" onClick={() => stopRecording()}><Square size={18} /></button><button type="button" aria-label="Cancel recording" onClick={() => stopRecording(true)}><X size={18} /></button></div> : null}
    <div className={styles.row}>{provider.capabilities.attachments && <button type="button" aria-label="Attach" disabled={disabled} onClick={() => setAttachMenu(!attachMenu)}><Paperclip size={19} /></button>}<SharedComposerInput ref={input} aria-label="Write a message" placeholder="Write a message" value={draft} disabled={disabled} rows={1} attachmentsEnabled={provider.capabilities.attachments && !disabled} onFiles={acceptFiles} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) { event.preventDefault(); void submit(); } }} />{provider.capabilities.audioSend && <button type="button" aria-label={recording ? 'Stop recording' : 'Hold to record'} disabled={disabled} onPointerDown={event => { touchRecord.current = event.pointerType === 'touch'; if (touchRecord.current) { event.preventDefault(); pointerStart.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); void startRecording(); } }} onPointerMove={event => { if (pointerStart.current !== null && event.clientX - pointerStart.current < -80) stopRecording(true); }} onPointerUp={() => { if (touchRecord.current) stopRecording(); }} onPointerCancel={() => stopRecording(true)} onClick={() => { if (!touchRecord.current) { if (recording) stopRecording(); else void startRecording(); } }}><Mic size={18} /></button>}<button className={styles.send} aria-label="Send message" disabled={disabled || sending || pending.some(item => item.uploading || item.error) || (!draft.trim() && !pending.some(item => item.attachment))}><ArrowUp size={20} /></button></div>
    <SharedComposerFileInput ref={files} multiple hidden onFiles={acceptFiles} /><SharedComposerFileInput ref={photos} accept="image/*" multiple hidden onFiles={acceptFiles} /><SharedComposerFileInput ref={camera} accept="image/*" capture="environment" hidden onFiles={acceptFiles} />
    {attachMenu && <div className={styles.attachMenu}><button type="button" onClick={() => { setAttachMenu(false); photos.current?.click(); }}><ImageIcon size={18} />Photo library</button><button type="button" onClick={() => void nativeCamera()}><Camera size={18} />Camera</button><button type="button" onClick={() => { setAttachMenu(false); files.current?.click(); }}><FileIcon size={18} />File</button>{driveProvider && <button type="button" onClick={() => { setAttachMenu(false); setDrive(true); }}><FileIcon size={18} />Google Drive</button>}</div>}{drive && driveProvider && <DrivePicker provider={driveProvider} targetProvider={provider.id} targetAccount={account} onClose={() => setDrive(false)} onFile={addDriveFile} onLink={(name, link) => setDraft(`${draft}${draft ? '\n' : ''}[${name}](${link})`)} />}
  </form>;
}
