'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { PointerEvent } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUp, Archive, Check, ChevronDown, Filter as FilterIcon, Inbox, MoreHorizontal, Search, Star, Paperclip, Clock, X, RefreshCw, CheckSquare, Mail, VolumeX, Pin, ExternalLink, Plus, Bold, Italic, Code, Link as LinkIcon } from 'lucide-react';
import { request, categories, isActionable, timestamp } from './client';
import { ProviderBadge } from './ProviderBadge';
import { FilterControls } from './FilterControls';
import { ActionBlock } from './ActionBlock';
import { MessageBody } from './MessageBody';
import type { Conversation, ConversationRow, Filter, Message, Provider, View } from './types';
import styles from './messages.module.css';
import { MailMessage, MailComposerFields, replyFields } from './MailMessage';
import type { MailFields, ReplyMode } from './MailMessage';
import { NewMessageSheet } from './NewMessageSheet';
import { MessageReactions, ThreadLinks } from './SlackDetails';
import { MessageComposer } from './MessageComposer';
import type { SendDraft } from './MessageComposer';
import { MessageMedia } from './MessageMedia';

const builtIns = [{ id: 'all', name: 'All' }, { id: 'agents', name: 'Agents' }, { id: 'mail', name: 'Mail' }, { id: 'chat', name: 'Chat' }];
const ROW_HEIGHT = 112;
const filterLabels: Record<string, string> = { unread: 'Unread', actionable: 'Needs me', starred: 'Starred', archived: 'Archived', hasAttachments: 'Attachments', deleted: 'Hidden', from: 'From', text: 'Search', providers: 'Provider', accounts: 'Account', labels: 'Labels', categories: 'Category', severity: 'Severity', dateFrom: 'From date', dateTo: 'To date', direction: 'Direction', conversationId: 'Conversation' };
function chipLabel(key: string, value: unknown, providers: Provider[]) { if (key === 'attachmentKind') return ({ image: 'Images', audio: 'Audio', file: 'Files' } as Record<string, string>)[String(value)]; if (typeof value === 'boolean') return filterLabels[key] || key; if (key === 'providers' && Array.isArray(value)) return value.map(id => providers.find(provider => provider.id === id)?.label || id).join(', '); if (key === 'accounts' && Array.isArray(value)) return value.map(id => providers.flatMap(provider => provider.accounts).find(account => account.id === id)?.label || id).join(', '); if (key === 'categories' && Array.isArray(value)) return value.map(id => categories[id] || id).join(', '); if (key === 'direction') return value === 'in' ? 'Received' : 'Sent'; if (key === 'dateFrom' || key === 'dateTo') return `${filterLabels[key]}: ${new Date(String(value)).toLocaleDateString('en-GB')}`; return `${filterLabels[key] || key}: ${Array.isArray(value) ? value.join(', ') : value}`; }
type StatePatch = Partial<Pick<Message, 'read' | 'archived' | 'deleted' | 'starred'>> & Partial<Pick<Conversation, 'muted' | 'pinned'>>;
function preview(message: Message) { if (!message) return ''; if (message.bodyText) return message.subject ? `${message.subject} · ${message.bodyText}` : message.bodyText; const audio = message.attachments.find(item => item.kind === 'audio'); if (audio) return `Voice note ${Math.floor((audio.durationMs || 0) / 60000)}:${String(Math.floor((audio.durationMs || 0) / 1000) % 60).padStart(2, '0')}`; return message.attachments.some(item => item.kind === 'image') ? 'Photo' : message.attachments[0] ? `File: ${message.attachments[0].name}` : ''; }
function initialFilter(tab: string, views: View[]): Filter { if (tab === 'all') return {}; if (tab === 'agents') return { kinds: ['system'] }; if (tab === 'mail') return { kinds: ['mail'] }; if (tab === 'chat') return { kinds: ['chat'] }; return views.find(view => view.id === tab)?.filter || {}; }

export function MessagesPage({ messageId }: { messageId?: string }) {
  const [rows, setRows] = useState<ConversationRow[]>([]); const [nextCursor, setNextCursor] = useState<string | null>(null); const loadingMore = useRef(false); const [providers, setProviders] = useState<Provider[]>([]); const [views, setViews] = useState<View[]>([]); const [counts, setCounts] = useState<Record<string, number>>({});
  const [tab, setTab] = useState('all'); const [filter, setFilter] = useState<Filter>({}); const [searchOpen, setSearchOpen] = useState(false); const [filterOpen, setFilterOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false);
  const [conversation, setConversation] = useState<Conversation | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [quickAction, setQuickAction] = useState<Message | null>(null);
  const [newMail, setNewMail] = useState(false); const [mailFields, setMailFields] = useState<MailFields>({ address: '', cc: '', subject: '' }); const [replyTarget, setReplyTarget] = useState<Message | null>(null); const [replyMode, setReplyMode] = useState<ReplyMode>('reply');
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [offline, setOffline] = useState(false); const [syncing, setSyncing] = useState(false); const [toast, setToast] = useState<{ text: string; undo?: () => void } | null>(null);
  const [scrollTop, setScrollTop] = useState(0); const [listHeight, setListHeight] = useState(700); const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false); const [conversationMenu, setConversationMenu] = useState(false);
  const pageRef = useRef<HTMLElement>(null); const listRef = useRef<HTMLDivElement>(null); const endRef = useRef<HTMLDivElement>(null); const messageListRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLTextAreaElement>(null); const toastTimer = useRef<ReturnType<typeof setTimeout>>(); const pressTimer = useRef<ReturnType<typeof setTimeout>>();
  const gesture = useRef<{ id: string; x: number; y: number; selected: boolean } | null>(null); const pullStart = useRef<number | null>(null); const conversationId = useRef<string | null>(null); conversationId.current = conversation?.id || null;
  const combined = useMemo(() => ({ ...initialFilter(tab, views), ...filter }), [tab, views, filter]); const combinedKey = JSON.stringify(combined); const filterKeyRef = useRef(combinedKey); filterKeyRef.current = combinedKey;
  const notice = useCallback((text: string, undo?: () => void) => { clearTimeout(toastTimer.current); setToast({ text, undo }); toastTimer.current = setTimeout(() => setToast(null), undo ? 5000 : 6500); }, []);
  const loadRows = useCallback(async () => { try { const data = await request<{ conversations: ConversationRow[]; nextCursor: string | null }>(`/conversations?filter=${encodeURIComponent(combinedKey)}`); if (filterKeyRef.current !== combinedKey) return; setRows(data.conversations.filter(row => row.lastMessage)); setNextCursor(data.nextCursor); setError(''); setOffline(!navigator.onLine); } catch (err) { setError(err instanceof Error ? err.message : 'Messages unavailable'); setOffline(!navigator.onLine); } finally { setLoading(false); } }, [combinedKey]);
  const loadMore = async () => { if (!nextCursor || loadingMore.current) return; loadingMore.current = true; const key = combinedKey; try { const data = await request<{ conversations: ConversationRow[]; nextCursor: string | null }>(`/conversations?filter=${encodeURIComponent(key)}&cursor=${encodeURIComponent(nextCursor)}`); if (filterKeyRef.current !== key) return; setRows(current => { const ids = new Set(current.map(row => row.id)); return [...current, ...data.conversations.filter(row => row.lastMessage && !ids.has(row.id))]; }); setNextCursor(data.nextCursor); } catch (err) { notice(err instanceof Error ? err.message : 'Could not load more messages.'); } finally { loadingMore.current = false; } };
  const refreshCounts = useCallback(async () => { const data = await request<{ counts: Record<string, number> }>('/counts'); setCounts(data.counts); window.dispatchEvent(new CustomEvent('messages.counts', { detail: data.counts })); }, []);
  const refreshConversation = useCallback(async (id: string) => { const data = await request<{ conversation: Conversation; messages: Message[] }>(`/conversations/${encodeURIComponent(id)}`); if (conversationId.current === id) { setConversation(data.conversation); setMessages(data.messages); } return data; }, []);
  useEffect(() => { void loadRows(); }, [loadRows]);
  useEffect(() => { void Promise.all([request<{ providers: Provider[] }>('/providers'), request<{ views: View[] }>('/views'), refreshCounts()]).then(([p, v]) => { setProviders(p.providers); setViews(v.views); }).catch(err => setError(err.message)); }, [refreshCounts]);
  useEffect(() => { const refresh = () => { void loadRows(); void refreshCounts().catch(() => {}); if (conversationId.current) void refreshConversation(conversationId.current).catch(err => notice(err.message)); }; const source = new EventSource('/api/messages/events'); source.addEventListener('messages.changed', refresh); source.addEventListener('providers.changed', () => void request<{ providers: Provider[] }>('/providers').then(data => setProviders(data.providers)).catch(err => notice(err.message))); const online = () => { setOffline(false); refresh(); }; const disconnected = () => setOffline(true); window.addEventListener('online', online); window.addEventListener('offline', disconnected); return () => { source.close(); window.removeEventListener('online', online); window.removeEventListener('offline', disconnected); }; }, [loadRows, refreshCounts, refreshConversation, notice]);
  useEffect(() => { if (!listRef.current) return; const observer = new ResizeObserver(entries => setListHeight(entries[0].contentRect.height)); observer.observe(listRef.current); return () => observer.disconnect(); }, []);
  useEffect(() => { const page = pageRef.current; const composer = page?.querySelector('[data-messages-composer]'); if (!page || !composer) { page?.style.setProperty('--messages-composer-height', '0px'); return; } const measure = () => page.style.setProperty('--messages-composer-height', `${composer.getBoundingClientRect().height}px`); measure(); const observer = new ResizeObserver(measure); observer.observe(composer); return () => observer.disconnect(); }, [conversation?.id, providers]);
  useEffect(() => { const list = messageListRef.current; if (list) list.scrollTop = list.scrollHeight; }, [messages.length, conversation?.id]);
  useEffect(() => { const input = inputRef.current; if (input) { input.style.height = 'auto'; input.style.height = `${Math.min(input.scrollHeight, 144)}px`; } }, [draft, conversation?.id]);
  useEffect(() => { if (!messageId) return; void request<{ message: Message }>(`/${encodeURIComponent(messageId)}`).then(async data => { conversationId.current = data.message.conversationId; const detail = await refreshConversation(data.message.conversationId); setConversation(detail.conversation); setMessages(detail.messages); setTimeout(() => { const target = document.getElementById(`message-${messageId}`); const list = messageListRef.current; if (target && list) list.scrollTop += target.getBoundingClientRect().top - list.getBoundingClientRect().top; }, 120); }).catch(err => setError(err.message)); }, [messageId, refreshConversation]);
  useEffect(() => () => { clearTimeout(toastTimer.current); clearTimeout(pressTimer.current); }, []);
  useEffect(() => {
    if (!filterOpen && !quickAction) return;
    const timer = setTimeout(() => {
      const dialog = Array.from(document.querySelectorAll<HTMLElement>('[role=dialog]')).find(item => item.getBoundingClientRect().height > 0);
      if (!dialog) return;
      const previous = document.activeElement as HTMLElement | null;
      const focusable = () => Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')).filter(item => item.getBoundingClientRect().height > 0);
      focusable()[0]?.focus();
      const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { setFilterOpen(false); setQuickAction(null); previous?.focus(); } if (event.key !== 'Tab') return; const items = focusable(); const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } };
      dialog.addEventListener('keydown', key);
      cleanup = () => { dialog.removeEventListener('keydown', key); previous?.focus(); };
    }, 0);
    let cleanup = () => {};
    return () => { clearTimeout(timer); cleanup(); };
  }, [filterOpen, quickAction?.id]);

  const providerFor = (id: string) => providers.find(provider => provider.id === id);
  const activeProvider = conversation ? providerFor(conversation.provider) : undefined;
  const readOnly = !!activeProvider?.setupHint || activeProvider?.health?.ok === false;
  const isMail = activeProvider?.kind === 'mail';
  const beginReply = (message: Message, mode: ReplyMode) => { setReplyTarget(message); setReplyMode(mode); setMailFields(replyFields(message, mode)); if (mode === 'forward') setDraft(`Forwarded message\nFrom: ${message.sender.name} <${message.sender.address || ''}>\nSubject: ${message.subject || ''}\n\n${message.bodyText.split('\n').map(line => `> ${line}`).join('\n')}`); requestAnimationFrame(() => inputRef.current?.focus()); };
  useEffect(() => { setReplyMode('reply'); const incoming = [...messages].reverse().find(message => message.direction === 'in'); setReplyTarget(incoming || null); if (incoming && isMail) setMailFields(replyFields(incoming, 'reply')); }, [conversation?.id, isMail]);
  const canDelete = (row: ConversationRow) => { const provider = providerFor(row.provider); return !!provider?.capabilities.delete && (provider.kind === 'mail' || row.lastMessage.sender.isMe || row.lastMessage.direction === 'out') && (!provider.deleteWindowSeconds || Date.now() - Date.parse(row.lastMessage.ts) <= provider.deleteWindowSeconds * 1000); };
  const updateState = async (row: ConversationRow, patch: StatePatch, undo = false) => {
    const provider = providerFor(row.provider);
    if (provider?.setupHint || provider?.health?.ok === false) { notice(`${provider.label} needs setup: ${provider.setupHint || provider.health?.reason}`); return; }
    const previousRows = rows; const previousMessages = messages; const previousConversation = conversation;
    const before: StatePatch = {}; for (const key of Object.keys(patch) as (keyof StatePatch)[]) (before as Record<string, unknown>)[key] = key === 'muted' || key === 'pinned' ? row[key] : row.lastMessage[key];
    setRows(current => current.map(item => item.id === row.id ? { ...item, ...patch, unreadCount: patch.read === undefined ? item.unreadCount : patch.read ? 0 : Math.max(1, item.unreadCount), lastMessage: { ...item.lastMessage, ...patch } } : item).filter(item => combined.archived || !item.archived).filter(item => combined.deleted || !item.lastMessage.deleted));
    if (conversation?.id === row.id) { setMessages(current => current.map(message => ({ ...message, ...patch }))); setConversation(current => current ? { ...current, ...patch } : current); }
    try { await request(`/conversations/${encodeURIComponent(row.id)}/state`, patch); void refreshCounts().catch(() => {}); if (undo) notice(patch.archived ? 'Archived.' : 'Hidden.', () => { void request(`/conversations/${encodeURIComponent(row.id)}/state`, before).then(() => loadRows()).catch(err => notice(err.message)); setToast(null); }); else if (patch.read) notice('Marked read'); }
    catch { setRows(previousRows); setMessages(previousMessages); setConversation(previousConversation); notice(`Could not update on ${providerFor(row.provider)?.label || row.provider}. Reverted.`); }
  };
  const openConversation = async (row: ConversationRow) => { if (selected.size) { toggleSelection(row.id); return; } conversationId.current = row.id; setConversation(row); setMessages([row.lastMessage]); setConversationMenu(false); try { const data = await refreshConversation(row.id); setConversation(data.conversation); setMessages(data.messages); if (row.unreadCount) void updateState(row, { read: true }); } catch (err) { notice(err instanceof Error ? err.message : 'Could not open conversation'); } };
  const answer = async (message: Message, value: string) => { await request(`/${encodeURIComponent(message.id)}/answer`, { answer: value }); const answered = { ...message, action: message.action ? { ...message.action, answer: value, answeredAt: new Date().toISOString() } : null }; setMessages(current => current.map(item => item.id === message.id ? answered : item)); setQuickAction(current => current?.id === message.id ? answered : current); await loadRows(); await refreshCounts(); };
  const toggleSelection = (id: string) => setSelected(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const hide = (row: ConversationRow) => void updateState(row, providerFor(row.provider)?.capabilities.archive ? { archived: true } : { deleted: true }, true);
  const pointerDown = (event: PointerEvent, row: ConversationRow) => { if ((event.target as HTMLElement).closest('button,input,a')) return; gesture.current = { id: row.id, x: event.clientX, y: event.clientY, selected: false }; clearTimeout(pressTimer.current); pressTimer.current = setTimeout(() => { if (gesture.current) gesture.current.selected = true; toggleSelection(row.id); }, 550); };
  const pointerUp = (event: PointerEvent, row: ConversationRow) => { clearTimeout(pressTimer.current); const start = gesture.current; gesture.current = null; if (!start || start.id !== row.id || start.selected) return; const dx = event.clientX - start.x; const dy = event.clientY - start.y; if (Math.abs(dx) > 65 && Math.abs(dx) > Math.abs(dy) * 1.3) { event.preventDefault(); if (dx > 0) void updateState(row, { read: row.unreadCount > 0 }); else hide(row); } else if (Math.abs(dx) < 8 && Math.abs(dy) < 8) void openConversation(row); };
  const sync = async () => { setSyncing(true); try { await request('/sync', { providers: combined.providers || providers.map(provider => provider.id) }); await loadRows(); } catch (err) { notice(err instanceof Error ? err.message : 'Could not sync. Retry.'); } finally { setSyncing(false); } };
  const createCard = async (message: Message) => { try { await request(`/${encodeURIComponent(message.id)}/card`, {}); notice('Card created'); await loadRows(); if (conversation) await refreshConversation(conversation.id); } catch (err) { notice(err instanceof Error ? err.message : 'Could not create card'); } };
  const bulk = async (patch: StatePatch | 'hide' | 'card') => { for (const row of rows.filter(item => selected.has(item.id))) { if (patch === 'card') await createCard(row.lastMessage); else await updateState(row, patch === 'hide' ? providerFor(row.provider)?.capabilities.archive ? { archived: true } : { deleted: true } : patch); } setSelected(new Set()); await loadRows(); };
  const send = async (content: SendDraft): Promise<boolean> => { if ((!content.markdown.trim() && !content.attachments.length) || !conversation || sending || readOnly || (isMail && !mailFields.address.trim())) return false; const text = content.markdown; setDraft(''); setSending(true); const local: Message = { id: `pending-${Date.now()}`, provider: conversation.provider, account: conversation.account, conversationId: conversation.id, externalId: null, direction: 'out', sender: { id: 'me', name: 'You', isMe: true }, recipients: [], subject: isMail ? mailFields.subject : null, bodyText: text, bodyMarkdown: text, bodyHtmlPath: null, attachments: content.attachments, ts: new Date().toISOString(), receivedTs: new Date().toISOString(), read: true, archived: false, deleted: false, starred: false, labels: [], category: null, severity: null, action: null, cardId: null, conversationRef: null, triage: null, rawPath: null, pending: true };
    setMessages(current => [...current, local]); try { const result = await request<{ queued?: boolean; item?: { id: string } }>('/outbox', { provider: conversation.provider, account: conversation.account, to: { ...(replyMode !== 'forward' ? { conversationId: conversation.id } : {}), ...(isMail ? mailFields : {}) }, body: { markdown: text }, attachments: content.attachments.map(item => ({ path: item.path, name: item.name, mime: item.mime, asVoiceNote: item.asVoiceNote })), replyToExternalId: replyMode === 'forward' ? null : replyTarget?.externalId || null, origin: 'user' }); await refreshConversation(conversation.id); await loadRows(); return true; } catch { setMessages(current => current.map(message => message.id === local.id ? { ...message, pending: false, failed: true } : message)); notice('Could not send. Retry.'); return false; } finally { setSending(false); } };
  const selectedRows = rows.filter(row => selected.has(row.id));
  const bulkCanArchive = selectedRows.length > 0 && selectedRows.every(row => providerFor(row.provider)?.capabilities.archive);
  const bulkCanDelete = selectedRows.length > 0 && selectedRows.every(canDelete);
  const first = Math.max(0, Math.floor(scrollTop / ROW_HEIGHT) - 4); const last = Math.min(rows.length, Math.ceil((scrollTop + listHeight) / ROW_HEIGHT) + 4);
  const activeRow = conversation && { ...conversation, lastMessage: messages[messages.length - 1] } as ConversationRow;
  const activeChips = Object.entries(filter).filter(([, value]) => value !== undefined && value !== '' && (!Array.isArray(value) || value.length));
  const selectTab = (id: string) => { setTab(id); setSelected(new Set()); setScrollTop(0); if (listRef.current) listRef.current.scrollTop = 0; };
  return <main ref={pageRef} className={`${styles.page} ${conversation ? styles.conversationOpen : ''}`} aria-label="Messages">
    <section className={styles.inboxPane} aria-label="Inbox"><header className={styles.header}><div><span className={styles.eyebrow}>YOUR INBOX</span><h1>Messages</h1></div><div className={styles.tools}><button title="Sync now" aria-label="Sync now" disabled={syncing} onClick={() => void sync()}><RefreshCw size={18} className={syncing ? styles.spin : ''} /></button><button aria-label="Filters" aria-expanded={filterOpen} onClick={() => setFilterOpen(!filterOpen)}><FilterIcon size={18} />{activeChips.length > 0 && <i className={styles.filterDot} />}</button><button aria-label="Search messages" onClick={() => setSearchOpen(!searchOpen)}><Search size={18} /></button><button aria-label="Messages menu" onClick={() => setMenuOpen(!menuOpen)}><MoreHorizontal size={19} /></button></div>{menuOpen && <nav className={styles.menu}>{providers.some(provider => provider.kind === 'mail' && provider.capabilities.send) && <button onClick={() => { setNewMail(true); setMenuOpen(false); }}>New mail</button>}<Link href="/messages/views">Views</Link><Link href="/messages/rules">Rules</Link><Link href="/messages/providers">Providers</Link><button onClick={() => { setSelected(new Set(rows.slice(0, 1).map(row => row.id))); setMenuOpen(false); }}>Select messages</button></nav>}</header>
      {searchOpen && <div className={styles.search}><Search size={17} /><input autoFocus aria-label="Search messages" placeholder="Search messages" value={filter.text || ''} onChange={event => setFilter({ ...filter, text: event.target.value || undefined })} /><button aria-label="Close search" onClick={() => { setSearchOpen(false); setFilter(current => ({ ...current, text: undefined })); }}><X size={16} /></button></div>}
      <div className={styles.tabs} role="tablist" aria-label="Inboxes">{[...builtIns, ...views.filter(view => !view.builtIn).sort((a, b) => a.order - b.order)].map(view => <button key={view.id} role="tab" aria-selected={tab === view.id} onClick={() => selectTab(view.id)}>{view.name}{counts[view.id] > 0 && <span>{counts[view.id]}</span>}</button>)}</div>
      {activeChips.length > 0 && <div className={styles.activeChips}>{activeChips.map(([key, value]) => <button key={key} onClick={() => setFilter(current => { const next = { ...current }; delete next[key as keyof Filter]; return next; })}>{chipLabel(key, value, providers)}<X size={12} /></button>)}<button onClick={() => setFilter({})}>Clear</button></div>}
      {filterOpen && <div className={styles.inlineFilters}><FilterControls filter={filter} onChange={setFilter} providers={providers} labels={Array.from(new Set(rows.flatMap(row => row.lastMessage.labels)))} agents={tab === 'all' || tab === 'agents'} /><footer><button onClick={() => setFilter({})}>Clear</button><button className={styles.primary} onClick={() => setFilterOpen(false)}>Show messages</button></footer></div>}
      {offline && <div className={styles.status} role="status">Offline. Showing your last messages.</div>}{error && <div className={styles.status} role="alert">{error}<button onClick={() => void loadRows()}>Retry</button></div>}
      {selected.size > 0 && <div className={styles.selectionHeader}><CheckSquare size={16} /><span>{selected.size} selected</span><button onClick={() => setSelected(new Set())}>Cancel</button></div>}
      <div className={styles.list} ref={listRef} onScroll={event => { setScrollTop(event.currentTarget.scrollTop); if (event.currentTarget.scrollHeight - event.currentTarget.scrollTop - event.currentTarget.clientHeight < ROW_HEIGHT * 6) void loadMore(); }} onTouchStart={event => { pullStart.current = event.currentTarget.scrollTop === 0 ? event.touches[0].clientY : null; }} onTouchEnd={event => { if (pullStart.current !== null && event.changedTouches[0].clientY - pullStart.current > 100) void sync(); pullStart.current = null; }} aria-label="Conversations">
        {loading ? <div className={styles.empty}>Loading messages…</div> : !rows.length ? <div className={styles.empty}><Inbox size={34} /><h2>{activeChips.length ? 'Nothing here.' : 'No messages yet.'}</h2>{activeChips.length ? <p>Filters hide {counts.all || 0} messages.</p> : <p>Your messages will appear here.</p>}</div> : <div style={{ height: rows.length * ROW_HEIGHT, position: 'relative' }}>{rows.slice(first, last).map((row, index) => <div key={row.id} data-testid="conversation-row" data-conversation-id={row.id} className={`${styles.row} ${row.unreadCount > 0 ? styles.unread : ''} ${selected.has(row.id) ? styles.selected : ''} ${row.lastMessage.severity === 'error' ? styles.rowError : row.lastMessage.severity === 'warning' ? styles.rowWarning : ''}`} style={{ top: (first + index) * ROW_HEIGHT, height: ROW_HEIGHT }} role="button" tabIndex={0} aria-label={`${row.title}${row.unreadCount ? ', unread' : ''}`} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); void openConversation(row); } }} onPointerDown={event => pointerDown(event, row)} onPointerMove={event => { if (gesture.current && Math.abs(event.clientY - gesture.current.y) > 10) clearTimeout(pressTimer.current); }} onPointerUp={event => pointerUp(event, row)} onPointerCancel={() => { clearTimeout(pressTimer.current); gesture.current = null; }}>
          {selected.size ? <input aria-label={`Select ${row.title}`} type="checkbox" checked={selected.has(row.id)} onChange={() => toggleSelection(row.id)} /> : <div className={styles.avatar}>{row.title.split(/\s+/).slice(0, 2).map(word => word[0]).join('').toUpperCase()}</div>}<div className={styles.rowText}><div className={styles.rowTitle}>{row.title}</div><div className={styles.preview}>{preview(row.lastMessage)}</div><div className={styles.rowMeta}>{isActionable(row.lastMessage) ? <button aria-label={`Needs you: Answer ${row.title}`} className={styles.needsYou} onClick={() => setQuickAction(row.lastMessage)}>Needs you<span className={styles.srOnly}>: Answer {row.title}</span></button> : row.lastMessage.category ? <span>{categories[row.lastMessage.category] || row.lastMessage.category}</span> : null}{row.lastMessage.attachments.length > 0 && <Paperclip size={13} aria-label="Has attachments" />}{row.lastMessage.starred && <Star size={13} fill="currentColor" aria-label="Starred" />}{row.muted && <VolumeX size={13} aria-label="Muted" />}{row.pinned && <Pin size={13} aria-label="Pinned" />}</div></div><div className={styles.rowRight}><time dateTime={row.lastMessageTs}>{row.unreadCount > 0 && <i className={styles.unreadDot} />}{timestamp(row.lastMessageTs)}</time><ProviderBadge provider={providerFor(row.provider)} id={row.provider} account={row.account} /></div>
        </div>)}</div>}
      </div>{selected.size > 0 && <div className={styles.bulkBar}><button onClick={() => void bulk({ read: true })}><Check size={17} />Mark read</button><button onClick={() => void bulk('hide')}><Archive size={17} />{bulkCanArchive ? 'Archive' : 'Hide'}</button>{bulkCanDelete && <button onClick={() => void bulk({ deleted: true })}><X size={17} />Delete</button>}<button onClick={() => void bulk({ starred: true })}><Star size={17} />Star</button><button onClick={() => void bulk('card')}><Plus size={17} />Create card</button></div>}
    </section>
    <section className={styles.conversationPane} aria-label="Conversation">{conversation ? <><header className={styles.conversationHeader}><button aria-label="Back to inbox" onClick={() => { setConversation(null); setMessages([]); if (messageId) window.history.replaceState({}, '', '/messages'); }}><ArrowLeft size={21} /></button><div className={styles.conversationHeading}><h2>{conversation.title}</h2><p>{conversation.participants.filter(person => !person.isMe).map(person => person.address || person.name).join(', ') || (conversation.provider === 'system' ? 'Garrison updates' : '')}</p><ProviderBadge provider={activeProvider} id={conversation.provider} account={conversation.account} /></div><button aria-label="Conversation menu" onClick={() => setConversationMenu(!conversationMenu)}><MoreHorizontal size={21} /></button>{conversationMenu && activeRow?.lastMessage && <div className={styles.menu}><button disabled={readOnly} onClick={() => { void updateState(activeRow, { read: false }); setConversationMenu(false); }}>Mark unread</button><button onClick={() => void updateState(activeRow, { muted: !conversation.muted })}>{conversation.muted ? 'Unmute' : 'Mute'}</button><button onClick={() => void updateState(activeRow, { pinned: !conversation.pinned })}>{conversation.pinned ? 'Unpin' : 'Pin'}</button>{activeProvider?.capabilities.archive && <button disabled={readOnly} onClick={() => hide(activeRow)}>Archive</button>}<button disabled={readOnly} onClick={() => void updateState(activeRow, { deleted: true }, true)}>{canDelete(activeRow) ? 'Delete' : 'Hide'}</button>{activeProvider?.capabilities.openInProvider && activeRow.lastMessage.deepLink && <a href={activeRow.lastMessage.deepLink} target="_blank" rel="noreferrer">Open in {activeProvider.label}<ExternalLink size={14} /></a>}<button onClick={() => void createCard(activeRow.lastMessage)}>Create card</button></div>}</header>
      {(activeProvider?.setupHint || activeProvider?.health?.ok === false) && <div className={styles.status}>{activeProvider.label} needs setup: {activeProvider.setupHint || activeProvider.health?.reason}</div>}
      <ThreadLinks conversation={conversation} rows={rows} onOpen={row => void openConversation(row)} /><div className={styles.messageList} ref={messageListRef}>{messages.map((message, index) => <div key={message.id} id={`message-${message.id}`} className={styles.messageWrap}>{(index === 0 || new Date(messages[index - 1].ts).toDateString() !== new Date(message.ts).toDateString()) && <div className={styles.dateSeparator}>{new Date(message.ts).toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })}</div>}<article className={`${styles.message} ${message.direction === 'out' ? styles.outgoing : ''} ${message.provider === 'system' ? styles.systemMessage : ''} ${message.id === messageId ? styles.highlight : ''}`}>
        <div className={styles.messageMeta}><strong>{message.provider === 'system' ? categories[message.category || ''] || 'Garrison' : message.sender.name}</strong><time dateTime={message.ts}>{timestamp(message.ts)}</time></div>{message.subject && message.subject !== message.bodyText && !isMail && <h3>{message.subject}</h3>}{isMail ? <MailMessage message={message} provider={activeProvider} onReply={beginReply} onChanged={() => { void loadRows(); if (conversation) void refreshConversation(conversation.id); }} /> : <MessageBody text={message.bodyText} markdown={message.bodyMarkdown} />}{activeProvider?.capabilities.reactionsRead && <MessageReactions message={message} />}<ActionBlock message={message} onAnswer={answer} />{message.cardId && <Link className={styles.openCard} href={`/embed/kanban-loop?card=${encodeURIComponent(message.cardId)}`}>Open card<ExternalLink size={14} /></Link>}<MessageMedia message={message} onRefresh={() => { if (conversation) void refreshConversation(conversation.id); }} onNotice={notice} />{message.pending && <span className={styles.sendStatus}><Clock size={13} />Sending</span>}{message.failed && <button className={styles.error} onClick={() => { setDraft(message.bodyText); setMessages(current => current.filter(item => item.id !== message.id)); inputRef.current?.focus(); }}>Could not send. Retry.</button>}{message.direction === 'out' && !message.pending && !message.failed && <span className={styles.sendStatus}><Check size={13} />Sent</span>}
      </article></div>)}<div ref={endRef} /></div>
      {activeProvider && (activeProvider.capabilities.send || activeProvider.capabilities.reply) && <MessageComposer key={conversation.id} provider={activeProvider} account={conversation.account} providers={providers} draft={draft} setDraft={setDraft} onSend={send} sending={sending} disabled={readOnly} textareaRef={inputRef}>{isMail && <MailComposerFields value={mailFields} onChange={setMailFields} />}</MessageComposer>}
    </> : <div className={styles.emptyConversation}><Mail size={42} strokeWidth={1} /><h2>All your messages, together.</h2><p>Choose a conversation to read and reply.</p><span>Garrison · Mail · Chat</span></div>}</section>
    {filterOpen && <div className={`${styles.sheetBackdrop} ${styles.filterBackdrop}`}  onClick={() => setFilterOpen(false)}><section className={styles.filterSheet} role="dialog" aria-modal="true" aria-label="Filters" onClick={event => event.stopPropagation()}><header><h2>Filters</h2><button aria-label="Close filters" onClick={() => setFilterOpen(false)}><X size={20} /></button></header><FilterControls filter={filter} onChange={setFilter} providers={providers} labels={Array.from(new Set(rows.flatMap(row => row.lastMessage.labels)))} agents={tab === 'all' || tab === 'agents'} /><footer><button onClick={() => setFilter({})}>Clear</button><button className={styles.primary} onClick={() => setFilterOpen(false)}>Show messages</button></footer></section></div>}
    {quickAction && <div className={styles.sheetBackdrop} onClick={() => setQuickAction(null)}><section className={styles.quickSheet} role="dialog" aria-modal="true" aria-label="Answer message" onClick={event => event.stopPropagation()}><header><h2>{quickAction.subject || categories[quickAction.category || ''] || 'Needs you'}</h2><button aria-label="Close answer" onClick={() => setQuickAction(null)}><X size={20} /></button></header><ProviderBadge provider={providerFor(quickAction.provider)} id={quickAction.provider} /><ActionBlock message={quickAction} onAnswer={answer} /></section></div>}
    {newMail && <NewMessageSheet providers={providers} onClose={() => setNewMail(false)} onSent={() => { notice('Message queued'); void loadRows(); }} />}
    {toast && <div className={styles.toast} role="status"><span>{toast.text}</span>{toast.undo && <button onClick={toast.undo}>Undo</button>}<button aria-label="Dismiss notification" onClick={() => setToast(null)}><X size={16} /></button></div>}
  </main>;
}
