'use client';
import { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
import type { Provider } from './types';
import { MailComposerFields } from './MailMessage';
import type { MailFields } from './MailMessage';
import { request, accountProblem } from './client';
import { MessageComposer } from './MessageComposer';
import type { SendDraft } from './MessageComposer';
import styles from './new-message.module.css';

export function NewMessageSheet({ providers, onClose, onSent }: { providers: Provider[]; onClose: () => void; onSent: () => void }) {
  const accounts = providers.filter(provider => provider.kind === 'mail' && provider.capabilities.send).flatMap(provider => provider.accounts.filter(account => !accountProblem(provider, account.id)).map(account => ({ key: `${provider.id}/${account.id}`, provider, account })));
  const [accountKey, setAccountKey] = useState(accounts[0]?.key || ''); const [fields, setFields] = useState<MailFields>({ address: '', cc: '', subject: '' }); const [markdown, setMarkdown] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { const element = dialog.current; if (!element) return; const previous = document.activeElement as HTMLElement; const focusable = () => Array.from(element.querySelectorAll<HTMLElement>('button:not(:disabled),select,input,textarea')); focusable()[0]?.focus({ preventScroll: true }); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key !== 'Tab') return; const items = focusable(), first = items[0], last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus({ preventScroll: true }); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus({ preventScroll: true }); } }; element.addEventListener('keydown', key); return () => { element.removeEventListener('keydown', key); previous?.focus({ preventScroll: true }); }; }, [onClose]);
  const target = accounts.find(item => item.key === accountKey);
  const send = async (content: SendDraft): Promise<boolean> => { if (!target || !fields.address.trim() || busy) return false; setBusy(true); setError(''); try { await request('/outbox', { provider: target.provider.id, account: target.account.id, to: fields, body: { markdown: content.markdown }, attachments: content.attachments.map(item => ({ path: item.path, name: item.name, mime: item.mime, asVoiceNote: item.asVoiceNote })), replyToExternalId: null, origin: 'user' }); onSent(); onClose(); return true; } catch (err) { setError(err instanceof Error ? err.message : 'Could not send. Retry.'); return false; } finally { setBusy(false); } };
  return <div className={styles.backdrop} onClick={onClose}><div className={styles.sheet} ref={dialog} role="dialog" aria-modal="true" aria-label="New mail" onClick={event => event.stopPropagation()}><header><h2>New mail</h2><button aria-label="Close new mail" onClick={onClose}><X size={20} /></button></header>{!target ? <p>No mail account is connected. Connect it in Connectors.</p> : <><label className={styles.account}>From account<select aria-label="From account" value={accountKey} onChange={event => setAccountKey(event.target.value)}>{accounts.map(item => <option value={item.key} key={item.key}>{item.provider.label} · {item.account.label}</option>)}</select></label>{error && <p role="alert">{error}</p>}<MessageComposer key={accountKey} provider={target.provider} account={target.account.id} providers={providers} draft={markdown} setDraft={setMarkdown} onSend={send} sending={busy} disabled={false}><MailComposerFields value={fields} onChange={setFields} /></MessageComposer></>}</div></div>;
}
