'use client';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowDown, ArrowUp, Bookmark, Briefcase, Heart, Inbox, Lock, Mail, MessageCircle, Star, Users, X } from 'lucide-react';
import { DndContext, PointerSensor, useSensor, useSensors, closestCenter } from '@dnd-kit/core';
import { SortableContext, useSortable, verticalListSortingStrategy, arrayMove } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import type { Filter, View } from './types';
import { request } from './client';
import styles from './management.module.css';
export const viewIcons = { Inbox, Mail, MessageCircle, Star, Users, Briefcase, Heart, Bookmark };
export function SaveViewDialog({ filter, view, onClose, onSaved }: { filter: Filter; view?: View; onClose: () => void; onSaved: (view: View) => void }) {
  const [name, setName] = useState(view?.name || ''); const [icon, setIcon] = useState(view?.icon || 'Inbox'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const save = async () => { if (!name.trim() || busy) return; setBusy(true); try { const result = await request<{ view: View }>('/views', { ...(view || {}), name: name.trim(), icon, filter, order: view?.order ?? 100 }); onSaved(result.view); onClose(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save this view.'); } finally { setBusy(false); } };
  return <div className={styles.backdrop} onClick={onClose}><form className={styles.dialog} role="dialog" aria-modal="true" aria-label={view ? 'Rename view' : 'Save as view'} onClick={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); void save(); }}><header><h2>{view ? 'Rename view' : 'Save as view'}</h2><button type="button" aria-label="Close view" onClick={onClose}><X size={20} /></button></header><label>Name<input autoFocus required value={name} onChange={event => setName(event.target.value)} /></label><fieldset><legend>Icon</legend><div className={styles.icons}>{Object.entries(viewIcons).map(([id, Glyph]) => <button key={id} type="button" aria-label={id} aria-pressed={icon === id} onClick={() => setIcon(id)}><Glyph size={20} /></button>)}</div></fieldset>{error && <p role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button className={styles.primary} disabled={busy || !name.trim()}>Save as view</button></footer></form></div>;
}
function SortableRow({ id, children }: { id: string; children: (drag: ReactNode) => ReactNode }) { const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id }); return <li ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }}>{children(<button className={styles.drag} aria-label="Drag to reorder" {...attributes} {...listeners}>⠿</button>)}</li>; }
export function ViewsPage() {
  const [views, setViews] = useState<View[]>([]); const [error, setError] = useState(''); const [editing, setEditing] = useState<View | 'new' | null>(null); const [notice, setNotice] = useState(''); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));
  const load = () => request<{ views: View[] }>('/views').then(data => setViews(data.views)).catch(err => setError(err.message)); useEffect(() => { void load(); }, []);
  const reorder = async (items: View[]) => { const old = views; const changed = items.map((view, order) => ({ ...view, order })); setViews(current => [...current.filter(view => view.builtIn), ...changed]); try { for (const view of changed) await request('/views', view); } catch (err) { setViews(old); setError(err instanceof Error ? err.message : 'Could not reorder views.'); } };
  const remove = async (view: View) => { try { const response = await fetch(`/api/messages/views/${encodeURIComponent(view.id)}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Could not delete view.'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not delete view.'); } };
  const custom = views.filter(view => !view.builtIn).sort((a, b) => a.order - b.order);
  return <main className={styles.page}><header className={styles.header}><Link href="/messages" aria-label="Back to messages"><ArrowLeft size={22} /></Link><div><span>MESSAGES</span><h1>Views</h1></div><button onClick={() => setEditing('new')}>New view</button></header>{error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.saved} role="status">{notice}</p>}<section className={styles.content}><p>Saved filters keep the messages you need close by.</p><ul className={styles.rows}>{(views.filter(view => view.builtIn).length ? views.filter(view => view.builtIn) : ['All', 'Agents', 'Mail', 'Chat'].map((name, order) => ({ id: name, name, builtIn: true, order, icon: 'Inbox', filter: {} }))).map(view => <li key={view.id}><Lock size={17} /><strong>{view.name}</strong><small>Built-in</small></li>)}</ul><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={({ active, over }) => { if (over && active.id !== over.id) void reorder(arrayMove(custom, custom.findIndex(view => view.id === active.id), custom.findIndex(view => view.id === over.id))); }}><SortableContext items={custom.map(view => view.id)} strategy={verticalListSortingStrategy}><ul className={styles.rows}>{custom.map((view, index) => <SortableRow key={view.id} id={view.id}>{drag => <>{drag}<strong>{view.name}</strong><div className={styles.rowActions}><button aria-label={`Move ${view.name} up`} disabled={index === 0} onClick={() => void reorder(arrayMove(custom, index, index - 1))}><ArrowUp size={16} /></button><button aria-label={`Move ${view.name} down`} disabled={index === custom.length - 1} onClick={() => void reorder(arrayMove(custom, index, index + 1))}><ArrowDown size={16} /></button><button onClick={() => setEditing(view)}>Rename</button><button onClick={() => void remove(view)}>Delete</button></div></>}</SortableRow>)}</ul></SortableContext></DndContext>{!custom.length && <p className={styles.empty}>No saved views yet.</p>}</section>{editing && <SaveViewDialog filter={editing === 'new' ? {} : editing.filter} view={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSaved={() => { setNotice('View saved'); void load(); }} />}</main>;
}
