import {test, expect, goto, checkpoint} from './fixture';
test('browses folders, renders files, copies relative paths and restores folder history', async ({page, app}, info) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await goto(page, app, `/projects/${app.id}/alpha/files`);
  await expect(page.locator('.projects-file-row').first()).toContainText('docs');
  await checkpoint(page, info, 'files', app);
  await page.locator('.projects-file-row').filter({hasText: 'docs'}).click();
  await page.locator('.projects-file-row').filter({hasText: 'deep'}).click();
  await page.locator('.projects-file-row').filter({hasText: 'note.md'}).click();
  await expect(page.getByRole('heading', {name: 'Synthetic guide', exact: true})).toBeVisible();
  await expect(page.locator('.projects-markdown li')).toHaveCount(2);
  await expect(page.locator('.projects-markdown')).toContainText('[[plain name]]');
  await expect(page.locator('.projects-markdown a')).toHaveCount(0);
  await page.getByRole('button', {name: 'Copy path', exact: true}).click();
  await expect(page.getByRole('status')).toHaveText('Path copied');
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('docs/deep/note.md');
  await checkpoint(page, info, 'viewer', app);
  await page.goBack(); await expect(page).toHaveURL(/path=docs%2Fdeep$/);
  await expect(page.locator('.projects-viewer')).toHaveCount(0);
  await page.locator('.projects-file-row').filter({hasText: 'example.ts'}).click();
  await expect(page.locator('.projects-line-numbers > span')).toHaveCount(3);
  await expect(page.locator('.projects-code code')).toContainText('const message');
  await page.goBack(); await page.locator('.projects-file-row').filter({hasText: 'pixel.png'}).click();
  await expect(page.locator('.projects-viewer img')).toBeVisible();
  await expect.poll(() => page.locator('.projects-viewer img').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1);
  const cold = await page.context().newPage();
  const {isolateShell} = await import('./fixture'); await isolateShell(cold, app);
  await cold.goto(app.base + `/projects/${app.id}/alpha/files?path=docs%2Fdeep%2Fnote.md`);
  await expect(cold.getByRole('heading', {name: 'Synthetic guide', exact: true})).toBeVisible();
  await cold.close();
});
