import { it,expect,vi } from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';import { execFileSync } from 'node:child_process';import { scratch,fixture } from './archive-test-helpers';
// @ts-ignore
import { importBoard } from '../packages/archive/src/trello/importer.mjs';
// @ts-ignore
import { TrelloClient } from '../packages/archive/src/trello/client.mjs';
const init=(dir:string)=>{for(const args of [['init'],['config','user.name','Archive fixture'],['config','user.email','archive@example.invalid'],['add','.'],['commit','--allow-empty','-m','Fixture baseline']])execFileSync('git',['-C',dir,...args],{stdio:'pipe'});};
it('tags before import, recovers after card four, skips IDs and never overwrites an authored name collision',async()=>{const s=await scratch({seed:false});try{
 init(s.vaultDir);s.service.queue.close();const board=JSON.parse(await fs.readFile(path.join(fixture,'trello-board.json'),'utf8'));const client={download:vi.fn(async()=>fs.readFile(path.join(fixture,'sample-document.jpg')))};const jobs=s.service.jobs;const row=await jobs.create('import-trello',{board,includeArchived:true});await expect(importBoard(s.ctx,jobs,row,{client,afterCard:(n:number)=>{if(n===4)throw new Error('Simulated process crash');}})).rejects.toThrow('Simulated');expect(row.summary.imported).toBe(4);expect(execFileSync('git',['-C',s.vaultDir,'tag','--list','archive/pre-import-*'],{encoding:'utf8'})).toContain(row.summary.tag);
 const next=await jobs.create('import-trello',{board,includeArchived:true});const recovered=await importBoard(s.ctx,jobs,next,{client});expect(recovered).toMatchObject({imported:5,skipped:4});const again=await importBoard(s.ctx,jobs,await jobs.create('import-trello',{board,includeArchived:true}),{client});expect(again).toMatchObject({imported:0,skipped:9});expect((await fs.readdir(path.join(s.vaultDir,'Archive'),{recursive:true})).some(n=>String(n).includes('.archive-import-'))).toBe(false);
 const one={...board,cards:[{...board.cards[0],id:'ffffffff0000000000000001'}]};const before=await s.read('Archive/Personal documents/Cartão de Cidadão/index.md');await importBoard(s.ctx,jobs,await jobs.create('import-trello',{board:one}),{client});expect(await s.read('Archive/Personal documents/Cartão de Cidadão/index.md')).toBe(before);expect(await s.read('Archive/Personal documents/Cartão de Cidadão (2)/index.md')).toContain('trello:ffffffff');
}finally{await s.close();}},15000);
it('authenticates Trello downloads only, bounds bytes, and respects Retry-After',async()=>{
 const fetchImpl=vi.fn().mockResolvedValueOnce(new Response(null,{status:302,headers:{location:'https://cdn.example.org/fixture'}})).mockResolvedValueOnce(new Response('fixture'));const client=new TrelloClient({key:'fixture-key',token:'fixture-token',fetchImpl});expect((await client.download('https://trello.com/attachment',{maxBytes:100})).toString()).toBe('fixture');expect(fetchImpl.mock.calls[0][1].headers.Authorization).toBe('OAuth oauth_consumer_key="fixture-key", oauth_token="fixture-token"');expect(fetchImpl.mock.calls[1][1].headers).toEqual({});await expect(client.download('https://example.org/file')).rejects.toThrow('Only Trello');
 const sleep=vi.fn(),log=vi.fn(),limited=new TrelloClient({key:'fixture-key',token:'fixture-token',sleep,log,fetchImpl:vi.fn().mockResolvedValueOnce(new Response(null,{status:429,headers:{'retry-after':'2'}})).mockResolvedValueOnce(Response.json([]))});await limited.boards();expect(sleep).toHaveBeenCalledWith(2000);expect(JSON.stringify(log.mock.calls)).not.toContain('fixture-token');
 const huge=new TrelloClient({key:'x',token:'y',fetchImpl:async()=>new Response('large',{headers:{'content-length':'300'}})});await expect(huge.download('https://trello.com/file',{maxBytes:20})).rejects.toMatchObject({oversize:true});
});
