import { it,expect,vi } from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';import { execFileSync } from 'node:child_process';import { scratch,fixture } from './archive-test-helpers';
const current=vi.hoisted(()=>({service:null as any}));
vi.mock('../src/app/api/archive/_context',()=>({archiveService:async()=>current.service}));
import * as handlers from '../src/app/api/archive/[[...path]]/route';
// @ts-ignore
import { createArchiveService } from '../packages/archive/src/service.mjs';
const routes=['GET status','GET tree','GET card','POST card','PATCH card','POST card/comment','DELETE card','POST list','PATCH list','DELETE list','GET note','PUT note','POST note/move','DELETE note','POST folder','POST upload','POST inbox/file','GET file','GET search','POST ingest/regenerate','POST ingest/retry-failed','GET jobs','GET jobs/id','POST jobs/id/cancel','GET trash','POST trash/restore','POST sync/now','POST import/trello/boards','POST import/trello/preview','POST import/trello/run','POST import/trello-json','POST look'];
async function call(route:string,method='GET',body?:any,headers:Record<string,string>={}){
 const req=new Request('http://fixture.test/api/archive/'+route,{method,headers:body&&!(body instanceof FormData)?{'content-type':'application/json',...headers}:headers,...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});
 const res=await (handlers as any)[method](req,{params:{path:route.split('?')[0].split('/')}});return {status:res.status,data:res.headers.get('content-type')?.includes('application/json')?await res.json():await res.arrayBuffer(),response:res};
}
it('exercises a positive handler journey for every API table row',async()=>{const board=JSON.parse(await fs.readFile(path.join(fixture,'trello-board.json'),'utf8'));const client={boards:async()=>[{id:board.id,name:board.name}],board:async()=>structuredClone(board),download:async()=>fs.readFile(path.join(fixture,'sample-document.jpg'))};const s=await scratch({seed:false,credentials:async()=>({TRELLO_KEY:'fixture',TRELLO_TOKEN:'fixture'}),clientFactory:()=>client,authorizeInternal:async(r:Request)=>r.headers.get('x-garrison-internal')==='fixture-token',look:async()=>({json:{pass:true,reasons:[]}})});current.service=s.service;const visited=new Set<string>();
 const ok=async(route:string,method='GET',body?:any,headers?:any)=>{const out=await call(route,method,body,headers);expect(out.status,method+' '+route+' '+JSON.stringify(out.data)).toBe(200);visited.add(method+' '+route.split('?')[0].replace(/jobs\/[a-f0-9-]+/,'jobs/id'));return out.data;};
 const settle=async(id:string)=>{for(let n=0;n<400;n++){const job=s.service.jobs.get(id);if(job.state==='done')return job;if(job.state==='failed')throw new Error(job.error);await new Promise(r=>setTimeout(r,10));}throw new Error('Import did not settle');};
 try{
  s.service.queue.close();for(const args of [['init'],['config','user.name','Fixture'],['config','user.email','fixture@example.invalid'],['add','.'],['commit','--allow-empty','-m','Fixture']])execFileSync('git',['-C',s.vaultDir,...args],{stdio:'pipe'});
  expect((await ok('status')).node).toBe('fixture-node');await ok('tree');const list=(await ok('list','POST',{title:'Test list'})).path;await ok('list','PATCH',{path:list,order:10});let card=(await ok('card','POST',{list,title:'Test card'})).path;let read=await ok('card?path='+encodeURIComponent(card));await ok('card','PATCH',{path:card,baseSha:read.sha,description:'Saved content'});await ok('card/comment','POST',{path:card,text:'A comment'});
  const form=new FormData();form.set('target',card);form.append('files[]',new Blob([await fs.readFile(path.join(fixture,'sample-document.jpg'))]),'image.jpg');await ok('upload','POST',form);await ok('file?path='+encodeURIComponent(card+'/image.jpg'));await ok('search?q=Saved&area=yours&kind=card');await ok('ingest/regenerate','POST',{path:card+'/image.jpg'});await ok('ingest/retry-failed','POST');await ok('jobs');const job=await s.service.jobs.create('import-trello',{});await ok('jobs/'+job.id);await ok('jobs/'+job.id+'/cancel','POST');
  await s.write('Archive/Inbox/file.txt','Inbox fixture');await ok('inbox/file','POST',{path:'Archive/Inbox/file.txt',toCard:card});await ok('folder','POST',{parent:'',name:'Memory'});await ok('note','PUT',{path:'Memory/New.md',markdown:'# New note',baseSha:'new'});await ok('note?path=Memory/New.md');await ok('folder','POST',{parent:'Memory',name:'Moved'});const moved=(await ok('note/move','POST',{path:'Memory/New.md',toFolder:'Memory/Moved'})).path;await ok('note','DELETE',{path:moved});const trashed=(await ok('card','DELETE',{path:card})).trashedTo;await ok('trash');await ok('trash/restore','POST',{entry:trashed});const empty=(await ok('list','POST',{title:'Empty'})).path;await ok('list','DELETE',{path:empty});await ok('sync/now','POST');
  await ok('import/trello/boards','POST');expect((await ok('import/trello/preview','POST',{boardId:board.id,includeArchived:true})).cards).toBe(9);await settle((await ok('import/trello/run','POST',{boardId:board.id,includeArchived:true})).jobId);
  const json=new FormData();json.set('export.json',new Blob([JSON.stringify(board)],{type:'application/json'}),'export.json');json.set('includeArchived','true');await settle((await ok('import/trello-json','POST',json)).jobId);
  await ok('look','POST',{imagePaths:[card+'/image.jpg'],prompt:'Judge fixture',schemaName:'judge'},{'x-garrison-internal':'fixture-token'});
  expect([...visited].sort()).toEqual([...routes].sort());
 }finally{await s.close();current.service=null;}
},20000);
it.each(routes)('rejects malformed or cross-origin input at %s',async row=>{const s=await scratch({seed:false});current.service=s.service;try{
 const [method,route]=row.split(' ');const out=method==='GET'?await call(route+'?path='+encodeURIComponent('../outside'),method):await call(route,method,{path:'../outside'},{origin:'https://other.invalid'});expect(out.status).toBe(403);
}finally{await s.close();current.service=null;}});
it('returns no_vault, validates upload and filters, and refuses a forged internal marker',async()=>{const s=await scratch({seed:false});current.service=s.service;try{
 expect((await call('search?area=unknown')).status).toBe(400);expect((await call('card','POST',{list:'Archive/Inbox'})).status).toBe(400);expect((await call('upload','POST',new FormData())).status).toBe(400);expect((await call('import/trello/boards','POST')).status).toBe(409);expect((await call('look','POST',{imagePaths:['Archive/Inbox/x.jpg'],prompt:'x',schemaName:'judge'},{'x-archive-authorized':'true'})).status).toBe(403);
 const missing=createArchiveService({home:s.home});current.service=missing;expect((await call('status'))).toMatchObject({status:409,data:{error:'no_vault'}});await missing.close();
}finally{await s.close();current.service=null;}});
