import { it,expect } from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';import { spawnSync } from 'node:child_process';import { scratch } from './archive-test-helpers';
// @ts-ignore
import { MATCHER,MESSAGE } from '../fittings/seed/basic-memory/scripts/archive-guard.mjs';
const script=path.join(process.cwd(),'fittings/seed/basic-memory/scripts/archive-guard.mjs');
function install(settings:string,vault:string,home:string,source:string){const result=spawnSync(process.execPath,[script,'--install',settings,vault,home,source],{encoding:'utf8'});expect(result.status,result.stderr).toBe(0);}
it('blocks every declared ownership path and allows ordinary memory tools',async()=>{const s=await scratch({seed:false});try{
 const settings=path.join(s.home,'settings.json');install(settings,s.vaultDir,s.home,script);await fs.symlink(path.join(s.vaultDir,'Archive'),path.join(s.root,'alias'));
 const blocked=[['Write',{file_path:path.join(s.vaultDir,'Archive/anything.md')}],['Edit',{file_path:path.join(s.vaultDir,'Archive/new.md')}],['MultiEdit',{file_path:path.join(s.vaultDir,'Memory/x.md'),new_path:path.join(s.vaultDir,'Archive/x.md')}],['NotebookEdit',{notebook_path:path.join(s.root,'alias/x.ipynb')}],['mcp__basic-memory__write_note',{folder:'Archive/Personal documents',title:'Test'}],['mcp__basic-memory__edit_note',{identifier:'memory://main/archive/personal/test'}],['mcp__basic-memory__move_note',{identifier:'Memory/x',destination_path:'Archive/Inbox/x'}],['mcp__basic-memory__move_note',{identifier:'Archive/old',destination_path:'Memory/x'}],['mcp__basic-memory__delete_note',{identifier:'archive/x'}],['Write',{file_path:path.join(s.root,'alias/new.md')}]];
 const allowed=[['Write',{file_path:path.join(s.vaultDir,'Memory/x.md')}],['Edit',{file_path:path.join(s.root,'code.ts')}],['mcp__basic-memory__write_note',{folder:'Projects/Garrison/Memory',title:'Decision'}],['mcp__basic-memory__move_note',{identifier:'memory/x',destination_path:'Projects/x'}],['mcp__basic-memory__delete_note',{identifier:'memory://main/memory/test'}]];
 const run=(row:any)=>spawnSync(process.execPath,[script,'--settings',settings,'--home',s.home],{input:JSON.stringify({tool_name:row[0],tool_input:row[1]}),encoding:'utf8'});
 for(const row of blocked){const result=run(row);expect(result.status,JSON.stringify(row)).toBe(2);expect(result.stderr).toBe(MESSAGE+'\n');expect(result.stdout).toBe('');}
 for(const row of allowed){const result=run(row);expect(result.status,JSON.stringify(row)).toBe(0);expect(result.stderr).toBe('');expect(result.stdout).toBe('');}
 const command=JSON.parse(await fs.readFile(settings,'utf8')).hooks.PreToolUse.find((g:any)=>g.matcher===MATCHER).hooks[0].command;const times=[];for(let i=0;i<8;i++){const start=performance.now();const result=spawnSync(command,{shell:true,input:JSON.stringify({tool_name:allowed[0][0],tool_input:allowed[0][1]}),encoding:'utf8'});expect(result.status).toBe(0);times.push(performance.now()-start);}times.sort((a,b)=>a-b);expect(times[3]).toBeLessThan(30);
}finally{await s.close();}},15000);
it('merges settings idempotently and refreshes a rendered vault path on settings change',async()=>{const s=await scratch({seed:false});try{
 const settings=path.join(s.home,'settings.json');await fs.writeFile(settings,JSON.stringify({hooks:{PreToolUse:[{matcher:'Bash',hooks:[{type:'command',command:'keep-existing'}]}]},permissions:{allow:['Read']}}));install(settings,s.vaultDir,s.home,script);install(settings,s.vaultDir,s.home,script);const data=JSON.parse(await fs.readFile(settings,'utf8'));expect(data.hooks.PreToolUse).toHaveLength(2);expect(data.hooks.PreToolUse[1].matcher).toBe(MATCHER);expect(data.permissions.allow).toEqual(['Read']);
}finally{await s.close();}});
