import {it,expect,vi,beforeEach} from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';
const state=vi.hoisted(()=>({tools:{} as Record<string,string|null>,calls:[] as any[]}));
vi.mock('../packages/archive/src/ingest/binaries.mjs',async importOriginal=>{
 const actual:any=await importOriginal();const find=(name:string)=>Object.hasOwn(state.tools,name)?state.tools[name]:actual.binary(name);const execute=async(command:string,args:string[])=>{
  if(command.startsWith('fixture-')){state.calls.push({command,args});const target=args.includes('--out')?args[args.indexOf('--out')+1]:args[1];await fs.copyFile(path.join(process.cwd(),'tests/fixtures/archive/sample-document.jpg'),target);return {stdout:'',stderr:''};}return actual.run(command,args);
 };return {...actual,binary:find,run:execute,imageForModel:(source:string,temp:string)=>actual.imageForModel(source,temp,{find,execute})};
});
import {scratch} from './archive-test-helpers';
// @ts-ignore ESM core
import {extract} from '../packages/archive/src/ingest/extract.mjs';
beforeEach(()=>{state.tools={sips:null,'heif-convert':null};state.calls=[];});
it('retains an unconvertible HEIC upload and writes an honest failed sidecar',async()=>{const s=await scratch({seed:false});try{const form=new FormData();form.set('target','Archive/Inbox');form.append('files[]',new Blob(['synthetic HEIC source']),'phone.heic');const uploaded=await s.request('upload','POST',form);expect(uploaded.data.files[0].path).toBe('Archive/Inbox/phone.heic');const result=await extract(s.ctx,'Archive/Inbox/phone.heic');expect(result).toMatchObject({kind:'image',status:'failed',error:'heic conversion unavailable on this node'});expect(await s.read('Archive/Inbox/phone.heic')).toBe('synthetic HEIC source');}finally{await s.close();}});
it.each(['sips','heif-convert'])('converts a HEIC upload using %s and keeps filename collisions intact',async tool=>{state.tools[tool]='fixture-'+tool;const s=await scratch({seed:false});try{await s.write('Archive/Inbox/phone.jpg','existing');const form=new FormData();form.set('target','Archive/Inbox');form.append('files[]',new Blob(['synthetic HEIC source']),'phone.heic');const result=await s.request('upload','POST',form);expect(result.data.files[0].path).toBe('Archive/Inbox/phone (2).jpg');expect(await s.read('Archive/Inbox/phone.jpg')).toBe('existing');expect(await fs.stat(path.join(s.vaultDir,'Archive/Inbox/phone.heic')).catch(()=>null)).toBeNull();expect(state.calls[0].command).toBe('fixture-'+tool);}finally{await s.close();}});

it('regenerates a stored HEIC after tools arrive without changing the original source',async()=>{const look=vi.fn(async(_input:any)=>({json:{what_it_is:'Fixture',text:'TEST-48392017',fields:[],language:'en',confidence:1}}));const s=await scratch({seed:false,look});try{const source='Archive/Inbox/stored.heic';await s.write(source,'Original HEIC fixture');expect((await extract(s.ctx,source)).status).toBe('failed');expect(look).not.toHaveBeenCalled();state.tools.sips='fixture-sips';expect((await extract(s.ctx,source)).status).toBe('ok');expect(look).toHaveBeenCalledOnce();expect(look.mock.calls[0][0].imagePaths[0]).toMatch(/converted\.jpg$/);expect(await s.read(source)).toBe('Original HEIC fixture');expect(await s.read(source+'.md')).toContain('source: stored.heic');}finally{await s.close();}});
