// Repo identity for coordination, keyed on the normalized ORIGIN URL rather
// than a filesystem path hash. On a mesh a path hash is doubly wrong: the same
// path on two machines is two different checkouts that would share a lock, and
// the same repo at two paths gets two locks.
//
//   https://github.com/Owner/Repo.git  -> github.com/Owner/Repo
//   git@github.com:Owner/Repo.git      -> github.com/Owner/Repo
//   ssh://git@host:2222/x/y            -> host/x/y
//
// The HOST is lowercased; the path is NOT (GitHub paths are case-sensitive).
// A repo with no origin gets `local:<node>:<hash16>` — explicitly node-scoped
// so it can never collide with another machine's different repo at the same
// path. This file is the single shared implementation: the coord-mcp fitting
// receives a generated byte-identical copy via scripts/sync-state-client.mjs.

import crypto from "node:crypto";

export function normalizeOriginUrl(url) {
  let s = String(url ?? "").trim();
  if (!s) return null;
  // scp-like: git@host:owner/repo(.git)
  const scp = s.match(/^([A-Za-z0-9._-]+)@([^:/]+):(.+)$/);
  if (scp && !s.includes("://")) {
    s = `${scp[2]}/${scp[3]}`;
  } else {
    s = s.replace(/^[A-Za-z][A-Za-z0-9+.-]*:\/\//, ""); // strip scheme
    s = s.replace(/^[^@/]+@/, ""); // strip userinfo
    // strip a :port on the host segment only
    const slash = s.indexOf("/");
    if (slash > 0) {
      const host = s.slice(0, slash).replace(/:\d+$/, "");
      s = `${host}${s.slice(slash)}`;
    }
  }
  s = s.replace(/\.git$/, "").replace(/\/+$/, "");
  const slash = s.indexOf("/");
  if (slash <= 0) return null;
  const host = s.slice(0, slash).toLowerCase();
  const rest = s.slice(slash + 1);
  if (!host || !rest) return null;
  return `${host}/${rest}`;
}

export function repoKeyForOrigin(originUrl, { node, fallbackPath } = {}) {
  const normalized = normalizeOriginUrl(originUrl);
  if (normalized) return normalized;
  const base = String(fallbackPath ?? "");
  const hash = crypto.createHash("sha1").update(base).digest("hex").slice(0, 16);
  return `local:${node ?? "unknown"}:${hash}`;
}
