import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import { startTalkApp, freePort, scratchHome, type TalkApp } from '../fixtures/talk-app';
let app: TalkApp;
test.beforeAll(async () => { app = await startTalkApp({ home: scratchHome('messages-connector-ui-'), gatewayUrl: `http://127.0.0.1:${await freePort()}`, port: await freePort() }); await fetch(`${app.base}/connectors`); });
test.afterAll(async () => app?.stop());
test('Slack adds a separate user workspace grant from Connectors without exposing its token', async ({ page }, info) => {
  const accounts: { id: string; label: string; address: string }[] = []; const submitted: unknown[] = [];
  await page.route('**/api/connectors', route => route.fulfill({ json: { connectors: [{ id: 'slack', fittingId: 'slack-channel', name: 'Slack', summary: 'Messages from your workspaces.', equipped: true, auth: 'api_key', secrets: [], sealed: true, statusKnown: true, actionCount: 2, mutatingActionCount: 1, hasTriggers: true }], vault: { unlocked: true, locked: false } } }));
  await page.route('**/api/vault/audit*', route => route.fulfill({ json: { entries: [] } }));
  await page.route('**/api/connectors/slack/messages-accounts', route => { if (route.request().method() === 'GET') return route.fulfill({ json: { accounts } }); submitted.push(route.request().postDataJSON()); const account = { id: 'workspace-fixture', label: 'Design workspace', address: 'Member fixture' }; accounts.push(account); return route.fulfill({ json: { account, missingScopes: [] } }); });
  await page.goto(`${app.base}/connectors`); await page.getByRole('button', { name: 'Add Messages account', exact: true }).click(); const form = page.getByRole('region', { name: 'Slack Messages accounts', exact: true }); await form.getByText('Required User Token Scopes', { exact: true }).click(); await expect(form.getByText(/channels:history, groups:history/)).toBeVisible(); await expect(form.getByRole('link', { name: 'Slack Apps', exact: true })).toHaveAttribute('href', 'https://api.slack.com/apps'); await form.scrollIntoViewIfNeeded(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await fs.mkdir('evidence/messages/p4', { recursive: true }); await page.screenshot({ path: `evidence/messages/p4/slack-account-setup-${info.project.name}.png` });
  const token = form.getByLabel('User OAuth Token', { exact: true }); await expect(token).toHaveAttribute('type', 'password'); await token.fill('xoxp-synthetic-fixture'); await form.getByRole('button', { name: 'Connect workspace', exact: true }).click(); await expect(form.getByRole('status')).toHaveText('Design workspace is connected to Messages.'); expect(submitted).toEqual([{ token: 'xoxp-synthetic-fixture' }]); await expect(form).not.toContainText('xoxp-synthetic-fixture'); await form.scrollIntoViewIfNeeded(); await page.screenshot({ path: `evidence/messages/p4/slack-account-connected-${info.project.name}.png` }); await form.getByRole('button', { name: 'Add Messages account', exact: true }).click(); await expect(form.getByLabel('User OAuth Token', { exact: true })).toHaveValue('');
});
