import type { Page, TestInfo } from '@playwright/test';
import { expect } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { Message, Conversation, ProviderDescriptor, Filter } from '../../../packages/messages/types';

export function seed() {
  const caps = { read: true as const, send: true, reply: true, markRead: true, archive: false, delete: true, groups: true, threads: true, attachments: true, audioReceive: true, audioSend: true, markdown: true, code: true, reactionsRead: false, openInProvider: false };
  const providers: ProviderDescriptor[] = [
    { id: 'system', kind: 'system', label: 'Garrison', badge: { text: 'Garrison', color: '#80601e', glyph: 'bot' }, accounts: [{ id: 'default', label: 'System' }], capabilities: { ...caps, send: false, reply: false, delete: false }, sync: { mode: 'stream' }, setupHint: null },
    { id: 'demo', kind: 'chat', label: 'Demo', badge: { text: 'Demo', color: '#31563f', glyph: 'message-circle' }, accounts: [{ id: 'fixture', label: 'Demo' }], capabilities: caps, sync: { mode: 'stream' }, setupHint: null },
    { id: 'google', kind: 'mail', label: 'Gmail', badge: { text: 'Gmail', color: '#963b32', glyph: 'mail' }, accounts: [{ id: 'personal', label: 'Personal' }, { id: 'work', label: 'Work' }], capabilities: { ...caps, archive: true }, sync: { mode: 'poll', intervalSeconds: 120 }, setupHint: 'Reconnect Google with mail read scope' },
  ];
  const now = new Date(); now.setHours(10, 24, 0, 0);
  const make = (id: string, title: string, extra: Partial<Message> = {}): Message => ({ id, provider: 'system', account: 'default', conversationId: `conversation-${id}`, externalId: id, direction: 'in', sender: { id: 'garrison', name: 'Garrison', isMe: false }, recipients: [], subject: title, bodyText: title, bodyMarkdown: null, bodyHtmlPath: null, attachments: [], ts: now.toISOString(), receivedTs: now.toISOString(), read: false, archived: false, deleted: false, starred: false, labels: [], category: 'card.done', severity: 'info', action: null, cardId: null, conversationRef: null, triage: null, rawPath: null, ...extra });
  const messages = [
    make('done', 'Release notes ready', { bodyText: 'The release notes are ready to read. All checks passed.', cardId: 'fixture-card-done' }),
    make('question', 'Choose a release date', { category: 'card.needs-input', bodyText: 'The schedule needs one decision from you.', action: { kind: 'question', prompt: 'Which day should we publish?', options: null, answeredAt: null, answer: null, revertUntil: null } }),
    make('approval', 'Approve the new outline', { category: 'card.needs-input', action: { kind: 'approval', prompt: 'Ready to apply the outline?', options: null, answeredAt: null, answer: null, revertUntil: null } }),
    make('revert', 'A rule was updated', { category: 'improver.decision', read: true, action: { kind: 'revert', prompt: 'You can restore the previous rule.', options: null, answeredAt: null, answer: null, revertUntil: new Date(Date.now() + 3600000).toISOString() } }),
    make('chat', 'Design workshop', { provider: 'demo', account: 'fixture', subject: null, category: null, sender: { id: 'alex', name: 'Alex', isMe: false }, bodyText: 'The updated component is ready. Here is the example.', bodyMarkdown: 'The **updated component** is ready.\n\n```ts\nconst inbox = messages.filter(m => !m.read);\n```', starred: true }),
    make('mail', 'Project notes for next week', { provider: 'google', account: 'work', sender: { id: 'client', name: 'Mara', address: 'mara@example.test', isMe: false }, bodyText: 'The notes and next steps are attached.', attachments: [{ id: 'fixture-image', kind: 'image', name: 'plan.png', mime: 'image/png', size: 1234, path: null, thumbPath: null, playbackPath: null, durationMs: null, transcript: null, transcriptStatus: 'none' }], category: null }),
    make('warning', 'Backup needs a retry', { severity: 'warning', category: 'system.warning', bodyText: 'The scheduled backup could not reach its destination.', read: true }),
  ];
  const conversations: Conversation[] = messages.map(message => ({ id: message.conversationId, provider: message.provider, account: message.account, externalId: message.externalId, kind: message.provider === 'system' ? 'system' : message.provider === 'google' ? 'mail-thread' : 'group', title: message.id === 'chat' ? 'Design workshop' : message.subject || message.sender.name, participants: [message.sender], lastMessageTs: message.ts, unreadCount: message.read ? 0 : 1, muted: false, pinned: false, archived: false, parentConversationId: null }));
  return { providers, messages, conversations, answers: [] as { id: string; answer: string }[], sent: [] as unknown[] };
}
export type FixtureState = ReturnType<typeof seed>;
function matches(message: Message, filter: Filter, state: FixtureState) { const provider = state.providers.find(item => item.id === message.provider); if (!filter.deleted && message.deleted || !filter.archived && message.archived) return false; if (filter.unread && message.read || filter.starred && !message.starred || filter.hasAttachments && !message.attachments.length) return false; if (filter.attachmentKind && !message.attachments.some(item => item.kind === filter.attachmentKind)) return false; if (filter.actionable && (!message.action || message.action.answeredAt || message.action.kind === 'info')) return false; if (filter.providers?.length && !filter.providers.includes(message.provider) || filter.kinds?.length && !filter.kinds.includes(provider!.kind)) return false; if (filter.from && !`${message.sender.name} ${message.sender.address || ''}`.toLowerCase().includes(filter.from.toLowerCase())) return false; if (filter.text && !`${message.subject || ''} ${message.bodyText} ${message.sender.name}`.toLowerCase().includes(filter.text.toLowerCase())) return false; if (filter.severity?.length && !filter.severity.includes(message.severity!)) return false; if (filter.categories?.length && !filter.categories.includes(message.category!)) return false; return true; }
export async function installFixtures(page: Page, state: FixtureState) {
  await page.route('**/api/messages**', async route => {
    const url = new URL(route.request().url()); const p = url.pathname.slice('/api/messages'.length); const body = route.request().method() === 'POST' ? route.request().postDataJSON() : null; const filter = JSON.parse(url.searchParams.get('filter') || '{}') as Filter;
    const json = (data: unknown, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(data) });
    if (p === '/events') return route.fulfill({ contentType: 'text/event-stream', body: ': fixture\n\n' });
    if (p === '/providers') return json({ providers: state.providers });
    if (p === '/views') return json({ views: [] });
    if (p === '/counts') { const available = state.messages.filter(message => !message.read && !message.deleted && !message.archived); return json({ counts: { all: available.length, agents: available.filter(message => message.provider === 'system').length, mail: available.filter(message => message.provider === 'google').length, chat: available.filter(message => message.provider === 'demo').length } }); }
    if (p === '/conversations') return json({ conversations: state.conversations.flatMap(conversation => { const messages = state.messages.filter(message => message.conversationId === conversation.id && matches(message, filter, state)); return messages.length ? [{ ...conversation, unreadCount: messages.filter(message => !message.read).length, lastMessage: messages[messages.length - 1] }] : []; }), nextCursor: null });
    if (/^\/conversations\/[^/]+\/state$/.test(p)) { const id = p.split('/')[2]; const conversation = state.conversations.find(item => item.id === id); if (conversation) Object.assign(conversation, body); for (const message of state.messages.filter(item => item.conversationId === id)) Object.assign(message, body); return json({ ok: true }); }
    if (/^\/conversations\/[^/]+$/.test(p)) { const id = p.split('/')[2]; return json({ conversation: state.conversations.find(item => item.id === id), messages: state.messages.filter(item => item.conversationId === id) }); }
    if (p.endsWith('/answer')) { const id = p.split('/')[1]; const message = state.messages.find(item => item.id === id)!; state.answers.push({ id, answer: body.answer }); message.action = { ...message.action!, answeredAt: new Date().toISOString(), answer: body.answer }; return json({ message }); }
    if (p === '/sync') return json({ ok: true });
    if (p.endsWith('/card')) { state.messages.find(item => item.id === p.split('/')[1])!.cardId = 'fixture-created-card'; return json({ card: { id: 'fixture-created-card' } }); }
    if (p === '/outbox') { state.sent.push(body); const original = state.messages.find(item => item.conversationId === body.to.conversationId)!; const message = { ...original, id: `sent-${state.sent.length}`, externalId: `sent-${state.sent.length}`, direction: 'out' as const, sender: { id: 'me', name: 'You', isMe: true }, bodyText: body.body.markdown, bodyMarkdown: body.body.markdown, read: true }; state.messages.push(message); return json({ item: { id: message.id, status: 'sent' } }); }
    const message = state.messages.find(item => item.id === p.slice(1)); if (message) return json({ message });
    return json({ error: `Unimplemented fixture endpoint ${p}` }, 404);
  });
}
export async function checkpoint(page: Page, info: TestInfo, name: string) { await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0); const dir = path.join(process.cwd(), 'evidence/messages/p2'); await fs.mkdir(dir, { recursive: true }); const file = path.join(dir, `${name}-${info.project.name}.png`); await page.screenshot({ path: file, fullPage: false }); await info.attach(name, { path: file, contentType: 'image/png' }); }
