import { test, expect } from '@playwright/test';
import type { TalkApp } from '../fixtures/talk-app';
import { startTalkApp, freePort, scratchHome } from '../fixtures/talk-app';
import { seed, installFixtures, checkpoint } from './fixtures';
import type { FixtureState } from './fixtures';
let app: TalkApp; let state: FixtureState;
test.beforeAll(async () => { app = await startTalkApp({ home: scratchHome('messages-ui-'), gatewayUrl: `http://127.0.0.1:${await freePort()}`, port: await freePort() }); await fetch(`${app.base}/messages`); });
test.afterAll(async () => { await app?.stop(); });
test.beforeEach(async ({ page }) => { state = seed(); await installFixtures(page, state); });

test('inbox groups conversations, shows badges and unread counts, and switches tabs', async ({ page }, info) => { await page.goto(`${app.base}/messages`); await expect(page.getByRole('heading', { name: 'Messages', exact: true })).toBeVisible(); await expect(page.getByRole('tab', { name: 'All 5', exact: true })).toBeVisible(); await expect(page.getByTestId('conversation-row')).toHaveCount(7); await expect(page.getByTestId('conversation-row').getByTestId('provider-badge')).toHaveCount(7); await checkpoint(page, info, 'inbox'); await page.getByRole('tab', { name: 'Chat 1', exact: true }).click(); await expect(page.getByTestId('conversation-row')).toHaveCount(1); await expect(page.getByRole('button', { name: 'Design workshop, unread', exact: true })).toBeVisible(); await page.getByRole('tab', { name: 'Agents 3', exact: true }).click(); await expect(page.getByTestId('conversation-row')).toHaveCount(5); });

test('done card opens from Agents and the message links to its card', async ({ page }, info) => { await page.goto(`${app.base}/messages`); await page.getByRole('tab', { name: 'Agents 3', exact: true }).click(); await page.getByRole('button', { name: 'Release notes ready, unread', exact: true }).click(); await expect(page.getByRole('link', { name: 'Open card', exact: true })).toHaveAttribute('href', '/embed/kanban-loop?card=fixture-card-done'); await expect(page.getByText('The release notes are ready to read. All checks passed.', { exact: true })).toBeVisible(); await checkpoint(page, info, 'done-conversation'); });

test('inline question answer reaches the structured signal and leaves Needs me', async ({ page }, info) => { await page.goto(`${app.base}/messages`); await page.getByRole('button', { name: 'Filters', exact: true }).click(); await page.getByRole('button', { name: 'Needs me', exact: true }).click(); await page.getByRole('button', { name: 'Show messages', exact: true }).click(); await page.locator('[data-conversation-id="conversation-question"]').getByRole('button', { name: 'Needs you: Answer Choose a release date', exact: true }).click(); await page.getByRole('textbox', { name: 'Your answer', exact: true }).fill('Friday morning'); await checkpoint(page, info, 'question'); await page.getByRole('button', { name: 'Send', exact: true }).click(); await expect(page.getByTestId('answered')).toHaveText('Answered: Friday morning'); expect(state.answers).toEqual([{ id: 'question', answer: 'Friday morning' }]); await page.getByRole('button', { name: 'Close answer', exact: true }).click(); await expect(page.locator('[data-conversation-id="conversation-question"]')).toHaveCount(0); });

test('approve and revert stay actionable inline with an honest countdown', async ({ page }, info) => { await page.goto(`${app.base}/messages/approval`); await expect(page.getByRole('button', { name: 'Approve', exact: true })).toBeVisible(); await checkpoint(page, info, 'approval'); await page.getByRole('button', { name: 'Approve', exact: true }).click(); await expect(page.getByTestId('answered')).toHaveText('Answered: approve'); await page.goto(`${app.base}/messages/revert`); await expect(page.getByText(/\d+:\d+ remaining/)).toBeVisible(); await checkpoint(page, info, 'revert'); await page.getByRole('button', { name: 'Revert', exact: true }).click(); await expect(page.getByTestId('answered')).toHaveText('Answered: revert'); expect(state.answers.map(item => item.answer)).toEqual(['approve', 'revert']); });

test('filters apply and clear and deep link opens the right conversation', async ({ page }, info) => { await page.goto(`${app.base}/messages`); await page.getByRole('button', { name: 'Filters', exact: true }).click(); await page.getByRole('button', { name: 'Unread', exact: true }).click(); await page.getByRole('textbox', { name: 'From', exact: true }).fill('Alex'); await checkpoint(page, info, 'filters'); await page.getByRole('button', { name: 'Show messages', exact: true }).click(); await expect(page.getByTestId('conversation-row')).toHaveCount(1); await page.getByRole('button', { name: 'Clear', exact: true }).click(); await expect(page.getByTestId('conversation-row')).toHaveCount(7); await page.goto(`${app.base}/messages/chat`); await expect(page.getByRole('heading', { name: 'Design workshop', exact: true })).toBeVisible(); await expect(page.locator('pre code')).toContainText('const inbox'); await checkpoint(page, info, 'chat-deep-link'); });

test('composer sends a fenced code snippet and shows the outgoing message', async ({ page }, info) => { await page.goto(`${app.base}/messages/chat`); const input = page.getByRole('textbox', { name: 'Write a message', exact: true }); await input.fill('A small example:\n\n```ts\nconst ready = true;\n```'); const inputBox = await input.boundingBox(); expect(inputBox!.y + inputBox!.height).toBeLessThanOrEqual(info.project.use.viewport!.height); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.getByText('You', { exact: true })).toBeVisible(); await expect(page.locator('pre code').filter({ hasText: 'const ready' })).toBeVisible(); expect(state.sent).toHaveLength(1); await checkpoint(page, info, 'composer-sent'); });

test('swipe toggles read, hide has undo, and multiselect exposes actions', async ({ page }, info) => { await page.goto(`${app.base}/messages`); const row = page.locator('[data-conversation-id="conversation-done"]'); const box = await row.boundingBox(); await row.dispatchEvent('pointerdown', { clientX: box!.x + 100, clientY: box!.y + 45, pointerId: 1, pointerType: 'touch' }); await row.dispatchEvent('pointerup', { clientX: box!.x + 195, clientY: box!.y + 45, pointerId: 1, pointerType: 'touch' }); await expect(row).toHaveAttribute('aria-label', 'Release notes ready'); await row.dispatchEvent('pointerdown', { clientX: box!.x + 220, clientY: box!.y + 45, pointerId: 2, pointerType: 'touch' }); await row.dispatchEvent('pointerup', { clientX: box!.x + 110, clientY: box!.y + 45, pointerId: 2, pointerType: 'touch' }); await expect(row).toHaveCount(0); await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(row).toBeVisible(); await row.dispatchEvent('pointerdown', { clientX: box!.x + 100, clientY: box!.y + 45, pointerId: 3, pointerType: 'touch' }); await page.waitForTimeout(600); await row.dispatchEvent('pointerup', { clientX: box!.x + 100, clientY: box!.y + 45, pointerId: 3, pointerType: 'touch' }); await page.getByRole('checkbox', { name: 'Select Choose a release date', exact: true }).check(); await expect(page.getByText('2 selected', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Mark read', exact: true })).toBeVisible(); await checkpoint(page, info, 'multiselect'); await page.getByRole('button', { name: 'Star', exact: true }).click(); expect(state.messages.find(message => message.id === 'done')!.starred).toBe(true); });

test('warm first paint is under two seconds and a thousand rows remain virtual', async ({ page }, info) => { const original = state.messages[4]; const conversation = state.conversations[4]; for (let i = 0; i < 1000; i++) { state.messages.push({ ...original, id: `bulk-${i}`, conversationId: `bulk-conv-${i}` }); state.conversations.push({ ...conversation, id: `bulk-conv-${i}`, title: `Fixture conversation ${i}` }); } await page.goto(`${app.base}/messages`); await expect(page.getByTestId('conversation-row').first()).toBeVisible(); await page.reload({ waitUntil: 'domcontentloaded' }); await expect(page.getByTestId('conversation-row').first()).toBeVisible(); const firstPaint = await page.evaluate(() => performance.getEntriesByName('first-contentful-paint')[0]?.startTime); expect(firstPaint).toBeGreaterThan(0); expect(firstPaint).toBeLessThan(2000); expect(await page.getByTestId('conversation-row').count()).toBeLessThan(25); await checkpoint(page, info, 'virtual-list'); });
