import { test, expect } from '@playwright/test';
import type { Page, TestInfo } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import type { TalkApp } from '../fixtures/talk-app';
import { startTalkApp, freePort, scratchHome } from '../fixtures/talk-app';
import { seed, installFixtures } from './fixtures';
import type { FixtureState } from './fixtures';
import type { Attachment } from '../../../packages/messages/types';
let app: TalkApp; let state: FixtureState; let photoPng: Buffer;
const photo = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420"><rect width="640" height="420" fill="#d8e2cf"/><path d="M0 330 190 160 300 265 470 100 640 300V420H0Z" fill="#577552"/><circle cx="130" cy="95" r="46" fill="#e4bb5c"/><text x="25" y="395" fill="#ffffff" font-family="sans-serif" font-size="24">Weekend walk</text></svg>');
function wav() { const rate = 8000, samples = rate * 3; const data = Buffer.alloc(44 + samples * 2); data.write('RIFF'); data.writeUInt32LE(data.length - 8, 4); data.write('WAVEfmt ', 8); data.writeUInt32LE(16, 16); data.writeUInt16LE(1, 20); data.writeUInt16LE(1, 22); data.writeUInt32LE(rate, 24); data.writeUInt32LE(rate * 2, 28); data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34); data.write('data', 36); data.writeUInt32LE(samples * 2, 40); for (let i = 0; i < samples; i++) data.writeInt16LE(Math.sin(i * 440 * 2 * Math.PI / rate) * 1800, 44 + i * 2); return data; }
const voice: Attachment = { id: 'voice-1', kind: 'audio', name: 'voice-note.m4a', mime: 'audio/mp4', size: 4096, path: 'fixture/audio.wav', playbackPath: 'fixture/audio.m4a', thumbPath: null, durationMs: 3000, transcript: 'Encontramo-nos no jardim depois do almoço.', transcriptStatus: 'done' };
const picture: Attachment = { id: 'photo-1', kind: 'image', name: 'weekend.png', mime: 'image/png', size: 2400, path: 'fixture/photo.png', playbackPath: null, thumbPath: 'fixture/photo.thumb.webp', durationMs: null, transcript: null, transcriptStatus: 'none' };
test.beforeAll(async () => { photoPng = await sharp(photo).png().toBuffer(); app = await startTalkApp({ home: scratchHome('messages-media-ui-'), gatewayUrl: `http://127.0.0.1:${await freePort()}`, port: await freePort() }); await fetch(`${app.base}/messages`); });
test.afterAll(async () => { await app?.stop(); });
test.beforeEach(async ({ page }) => { state = seed(); const provider = state.providers.find(item => item.id === 'demo')!; provider.id = 'whatsapp-web'; provider.label = 'WhatsApp'; provider.badge = { text: 'WhatsApp', color: '#315f43', glyph: 'message-circle' }; provider.deleteWindowSeconds = 172800; provider.accounts[0].label = 'Personal'; const message = state.messages.find(item => item.id === 'chat')!; message.provider = provider.id; message.bodyText = 'Here is the photo from our walk.'; message.bodyMarkdown = null; message.attachments = [picture]; const conversation = state.conversations.find(item => item.id === message.conversationId)!; conversation.provider = provider.id; conversation.title = 'Weekend plans'; conversation.participants = [message.sender, { id: 'jo', name: 'Jo', isMe: false }]; await installFixtures(page, state);
  await page.route('**/api/messages/attachments**', async route => { if (route.request().method() === 'POST') { const body = route.request().postDataJSON(); return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ attachment: { ...picture, id: `upload-${Date.now()}`, name: body.name, mime: body.mime, size: Buffer.from(body.base64, 'base64').length, kind: body.mime.startsWith('audio/') ? 'audio' : body.mime.startsWith('image/') ? 'image' : 'file', path: `fixture/${body.name}`, playbackPath: body.mime.startsWith('audio/') ? `fixture/${body.name}` : null, durationMs: body.mime.startsWith('audio/') ? 3000 : null } }) }); } const audio = route.request().url().includes('voice-1'); await route.fulfill({ contentType: audio ? 'audio/wav' : 'image/svg+xml', body: audio ? wav() : photo }); });
  await page.route('**/api/messages/drive**', async route => { if (route.request().method() === 'POST') { const body = route.request().postDataJSON(); return route.fulfill({ contentType: 'application/json', body: JSON.stringify(body.fileId === 'large' ? { link: 'https://drive.google.com/file/d/large/view', name: 'Long recording' } : { attachment: { ...picture, id: 'drive-plan', name: 'Shared plan.pdf', kind: 'file', mime: 'application/pdf', path: 'fixture/shared-plan.pdf' } }) }); } return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ accounts: [{ id: 'work', label: 'Work' }], account: 'work', files: [{ id: 'plan', name: 'Shared plan.pdf', mimeType: 'application/pdf', size: '2000' }, { id: 'large', name: 'Long recording', mimeType: 'audio/mp4', size: '30000000' }] }) }); });
});
async function capture(page: Page, info: TestInfo, phase: string, name: string) { const dismiss = page.getByRole('button', { name: 'Dismiss notification', exact: true }); if (await dismiss.isVisible() && !(await page.getByRole('dialog').count())) await dismiss.click(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && scrollY === 0)).toBe(true); const composer = page.locator('[data-messages-composer]'); if (await composer.count() && !(await page.getByRole('dialog').count())) { await expect(composer).toBeVisible(); await expect.poll(async () => (await composer.boundingBox())!.y + (await composer.boundingBox())!.height <= (page.viewportSize()?.height || 0)).toBe(true); } if (info.project.name === 'iphone' && !(await page.getByRole('dialog').count())) expect((await page.locator('.app-bar').boundingBox())!.y).toBe(0); await expect(page.getByText('Could not play this voice note.', { exact: true })).toHaveCount(0); const folder = path.join(process.cwd(), `evidence/messages/${phase}`); await fs.mkdir(folder, { recursive: true }); const file = path.join(folder, `${name}-${info.project.name}.png`); await page.screenshot({ path: file }); await info.attach(name, { path: file, contentType: 'image/png' }); }

test('WhatsApp journey discovers group photo, opens fullscreen and replies', async ({ page }, info) => { await page.goto(`${app.base}/messages`); const row = page.locator('[data-conversation-id="conversation-chat"]'); await expect(row).toContainText('WhatsApp'); await expect(row).toContainText('Weekend plans'); await capture(page, info, 'p5', 'group-inbox'); await row.click(); await page.getByRole('button', { name: 'Open photo weekend.png', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'weekend.png', exact: true })).toBeVisible(); await capture(page, info, 'p5', 'photo-viewer'); await page.getByRole('button', { name: 'Zoom in', exact: true }).click(); await capture(page, info, 'p5', 'photo-viewer-zoomed'); await page.getByRole('button', { name: 'Close photo', exact: true }).click(); await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('See you at the weekend.'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.getByLabel('Conversation', { exact: true }).getByText('See you at the weekend.', { exact: true })).toBeVisible(); expect((state.sent[0] as any).origin).toBe('user'); await capture(page, info, 'p5', 'group-replied'); });

test('voice note journey plays at 1.5x, searches transcript and replies with a photo', async ({ page }, info) => { const message = state.messages.find(item => item.id === 'chat')!; message.bodyText = ''; message.attachments = [voice]; await page.goto(`${app.base}/messages/chat`); await expect(page.getByText(voice.transcript!, { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Play voice note', exact: true }).click(); await page.getByRole('combobox', { name: 'Playback speed', exact: true }).selectOption('1.5'); await expect.poll(() => page.locator('audio').evaluate((element: HTMLAudioElement) => element.playbackRate)).toBe(1.5); await expect.poll(() => page.locator('audio').evaluate((element: HTMLAudioElement) => element.currentTime)).toBeGreaterThan(0); await expect(page.locator('audio')).toHaveJSProperty('paused', false); await capture(page, info, 'p6', 'voice-player'); await page.getByRole('button', { name: 'Pause voice note', exact: true }).click(); if (info.project.name === 'iphone') await page.getByRole('button', { name: 'Back to inbox', exact: true }).click(); await page.getByRole('button', { name: 'Search messages', exact: true }).click(); await page.getByRole('textbox', { name: 'Search messages', exact: true }).fill('jardim'); await expect(page.locator('[data-conversation-id="conversation-chat"]')).toBeVisible(); await capture(page, info, 'p6', 'transcript-search'); await page.locator('[data-conversation-id="conversation-chat"]').click(); await page.getByRole('button', { name: 'Attach', exact: true }).click(); const chooser = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'Photo library', exact: true }).click(); await (await chooser).setFiles({ name: 'library-photo.png', mimeType: 'image/png', buffer: photoPng }); await expect(page.getByRole('button', { name: 'Remove library-photo.png', exact: true })).toBeVisible(); await capture(page, info, 'p6', 'photo-attached'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect.poll(() => state.sent.length).toBe(1); expect((state.sent[0] as any).attachments[0].name).toBe('library-photo.png'); });

test('shared composer accepts pasted images, files and Google Drive links', async ({ page }, info) => { await page.goto(`${app.base}/messages/chat`); await page.getByRole('textbox', { name: 'Write a message', exact: true }).evaluate(element => { const transfer = new DataTransfer(); transfer.items.add(new File([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z6VIAAAAASUVORK5CYII='), char => char.charCodeAt(0))], 'pasted.png', { type: 'image/png' })); element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true })); }); await expect(page.getByRole('button', { name: 'Remove pasted.png', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Attach', exact: true }).click(); const chooser = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'File', exact: true }).click(); await (await chooser).setFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Fixture notes') }); await expect(page.getByRole('button', { name: 'Remove notes.txt', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Attach', exact: true }).click(); await page.getByRole('button', { name: 'Google Drive', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Google Drive', exact: true })).toBeVisible(); await capture(page, info, 'p6', 'drive-picker'); await page.getByRole('button', { name: /Long recording/ }).click(); await expect(page.getByRole('textbox', { name: 'Write a message', exact: true })).toHaveValue('[Long recording](https://drive.google.com/file/d/large/view)'); await page.getByRole('button', { name: 'Remove pasted.png', exact: true }).click(); await capture(page, info, 'p6', 'file-and-link'); });

test('synthetic microphone records a voice note and sends it as a structured attachment', async ({ page }, info) => { await page.addInitScript(() => { const context = new AudioContext(); document.addEventListener('click', () => { void context.resume(); }, { once: true }); Object.defineProperty(navigator.mediaDevices, 'getUserMedia', { value: async () => { await context.resume(); const oscillator = context.createOscillator(); oscillator.frequency.value = 440; const destination = context.createMediaStreamDestination(); oscillator.connect(destination); oscillator.start(); return destination.stream; } }); }); await page.goto(`${app.base}/messages/chat`); const mic = page.getByRole('button', { name: 'Hold to record', exact: true }); await mic.dispatchEvent('pointerdown', { pointerType: 'mouse', pointerId: 1 }); await mic.click(); await expect(page.getByText(/Recording 0:/)).toBeVisible(); await page.waitForTimeout(550); await page.getByRole('button', { name: 'Stop recording', exact: true }).first().click(); await expect(page.getByRole('button', { name: 'Send voice note', exact: true })).toBeVisible(); await capture(page, info, 'p6', 'voice-preview'); await page.getByRole('button', { name: 'Send voice note', exact: true }).click(); await expect.poll(() => state.sent.length).toBe(1); expect((state.sent[0] as any).attachments[0].asVoiceNote).toBe(true); expect((state.sent[0] as any).attachments[0].mime).toMatch(/^audio\//); });


test('recording can be cancelled and restarted with touch on phone or clicks on desktop', async ({ page }, info) => {
  await page.addInitScript(() => { const context = new AudioContext(); document.addEventListener('click', () => { void context.resume(); }, { once: true }); Object.defineProperty(navigator.mediaDevices, 'getUserMedia', { value: async () => { await context.resume(); const oscillator = context.createOscillator(); const destination = context.createMediaStreamDestination(); oscillator.connect(destination); oscillator.start(); return destination.stream; } }); });
  await page.goto(`${app.base}/messages/chat`); await page.getByRole('textbox', { name: 'Write a message', exact: true }).click(); const mic = page.locator('[data-voice-recorder]'); if (info.project.name === 'desktop') { await mic.click(); await expect(page.getByText(/Recording 0:/)).toBeVisible(); await page.getByRole('button', { name: 'Cancel recording', exact: true }).click(); await expect(page.getByRole('button', { name: 'Send voice note', exact: true })).toHaveCount(0); await mic.click(); await expect(page.getByText(/Recording 0:/)).toBeVisible(); await page.waitForTimeout(350); await mic.click(); await expect(page.getByRole('button', { name: 'Send voice note', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); expect(state.sent).toEqual([]); return; } const session = await page.context().newCDPSession(page); const box = (await mic.boundingBox())!; const x = box.x + box.width / 2, y = box.y + box.height / 2;
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] }); await expect(page.getByText(/Recording 0:/)).toBeVisible(); await page.waitForTimeout(350); await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 100, y }] }); await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await expect(page.getByText(/Recording 0:/)).toHaveCount(0); await expect(page.getByRole('button', { name: 'Send voice note', exact: true })).toHaveCount(0);
  const next = (await mic.boundingBox())!; await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: next.x + next.width / 2, y: next.y + next.height / 2 }] }); await expect(page.getByText(/Recording 0:/)).toBeVisible(); await page.waitForTimeout(350); await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await expect(page.getByRole('button', { name: 'Send voice note', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); expect(state.sent).toEqual([]);
});
