import { test, expect } from '@playwright/test';
import type { Page, TestInfo } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { TalkApp } from '../fixtures/talk-app';
import { startTalkApp, freePort, scratchHome } from '../fixtures/talk-app';
import { seed, installFixtures } from './fixtures';
import type { FixtureState } from './fixtures';
let app: TalkApp; let state: FixtureState;
test.beforeAll(async () => { app = await startTalkApp({ home: scratchHome('messages-providers-ui-'), gatewayUrl: `http://127.0.0.1:${await freePort()}`, port: await freePort() }); await fetch(`${app.base}/messages`); });
test.afterAll(async () => { await app?.stop(); });
async function capture(page: Page, info: TestInfo, phase: string, screen: string) { const toast = page.getByRole('button', { name: 'Dismiss notification', exact: true }); if (await toast.isVisible()) await toast.click(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && window.scrollY === 0)).toBe(true); if (info.project.name === 'iphone') { const bar = page.locator('.app-bar'); await expect(bar).toBeVisible(); expect((await bar.boundingBox())!.y).toBe(0); } const folder = path.join(process.cwd(), `evidence/messages/${phase}`); await fs.mkdir(folder, { recursive: true }); const file = path.join(folder, `${screen}-${info.project.name}.png`); await page.screenshot({ path: file }); await fs.writeFile(file.replace('.png', '.layout.json'), JSON.stringify(await page.evaluate(() => ({ scrollY, visualViewport: { top: visualViewport?.offsetTop, scale: visualViewport?.scale }, appBar: document.querySelector('.app-bar')?.getBoundingClientRect().toJSON(), shell: document.querySelector('.shell-content')?.getBoundingClientRect().toJSON() })), null, 2)); await info.attach(screen, { path: file, contentType: 'image/png' }); }
test.beforeEach(async ({ page }) => {
  state = seed(); state.providers.find(item => item.id === 'google')!.setupHint = null;
  const mail = state.messages.find(item => item.id === 'mail')!; mail.bodyHtmlPath = 'html/mail.html'; mail.recipients = [{ id: 'me', name: 'You', address: 'me@example.test', isMe: true }, { id: 'colleague', name: 'Jo', address: 'jo@example.test', isMe: false }]; mail.deepLink = 'https://mail.google.com/mail/u/0/#inbox/fixture-mail';
  state.providers.find(item => item.id === 'google')!.capabilities.openInProvider = true;
  await installFixtures(page, state);
  await page.route('**/api/messages/mail/html**', route => route.fulfill({ contentType: 'text/html', body: `<p>Here is the <strong>release overview</strong>.</p><p>Everything is ready for review.</p>${new URL(route.request().url()).searchParams.has('images') ? '<p>Images loaded for this message.</p>' : '<img alt="Remote image" data-message-image="0">'}<p><a href="https://example.test/release" target="_blank">Read the release notes</a></p>` }));
});

test('Gmail journey filters images, renders inert HTML, loads images and replies with fenced code', async ({ page }, info) => {
  await page.goto(`${app.base}/messages`); await page.getByRole('tab', { name: 'Mail 1', exact: true }).click(); await page.getByRole('button', { name: 'Filters', exact: true }).click(); await page.getByRole('button', { name: 'Unread', exact: true }).click(); await page.getByRole('button', { name: 'Images', exact: true }).click(); await page.getByRole('button', { name: 'Show messages', exact: true }).click(); await page.locator('[data-conversation-id="conversation-mail"]').click();
  const frame = page.getByTitle('Mail from Mara', { exact: true }); await expect(frame).toHaveAttribute('sandbox', ''); await expect(page.frameLocator('iframe[title="Mail from Mara"]').getByText('release overview')).toBeVisible(); await page.getByRole('button', { name: 'Load images', exact: true }).click(); await expect(page.frameLocator('iframe[title="Mail from Mara"]').getByText('Images loaded for this message.')).toBeVisible(); await capture(page, info, 'p3', 'mail-thread');
  await page.getByRole('button', { name: 'Reply', exact: true }).click(); await expect(page.getByRole('textbox', { name: 'To', exact: true })).toHaveValue('mara@example.test'); await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('Looks good.\n\n```ts\nconst approved = true;\n```'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.getByText('You', { exact: true }).first()).toBeVisible(); await expect(page.locator('pre code').filter({ hasText: 'const approved' })).toBeVisible(); expect(state.sent).toHaveLength(1); expect((state.sent[0] as any).to.address).toBe('mara@example.test'); await capture(page, info, 'p3', 'mail-replied');
});

test('Gmail reply all and forward preserve recipient intent and capability actions', async ({ page }, info) => {
  await page.goto(`${app.base}/messages/mail`); await page.getByRole('button', { name: 'Reply all', exact: true }).click(); await expect(page.getByRole('textbox', { name: 'Cc', exact: true })).toHaveValue('jo@example.test'); await expect(page.getByRole('textbox', { name: 'Subject', exact: true })).toHaveValue('Re: Project notes for next week'); await capture(page, info, 'p3', 'reply-all');
  await page.getByRole('button', { name: 'Forward', exact: true }).click(); await expect(page.getByRole('textbox', { name: 'To', exact: true })).toHaveValue(''); await expect(page.getByRole('textbox', { name: 'Subject', exact: true })).toHaveValue('Fwd: Project notes for next week'); await page.getByRole('button', { name: 'Conversation menu', exact: true }).click(); await expect(page.getByRole('link', { name: 'Open in Gmail', exact: true })).toHaveAttribute('href', 'https://mail.google.com/mail/u/0/#inbox/fixture-mail'); await expect(page.getByRole('button', { name: 'Archive', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Delete', exact: true })).toBeVisible();
});

test('Slack journey opens a channel thread, shows reactions and sends code into that thread', async ({ page }, info) => {
  const provider = state.providers.find(item => item.id === 'demo')!; provider.id = 'slack'; provider.label = 'Slack'; provider.badge = { text: 'Slack', color: '#6b477b', glyph: 'hash' }; provider.capabilities.reactionsRead = true; provider.capabilities.openInProvider = true;
  const message = state.messages.find(item => item.id === 'chat')!; message.provider = 'slack'; message.externalId = 'C1:123.002'; message.reactions = [{ name: 'thumbsup', count: 3 }]; message.deepLink = 'https://app.slack.com/client/T1/C1/thread/C1-123.001';
  const child = state.conversations.find(item => item.id === 'conversation-chat')!; child.provider = 'slack'; child.title = 'component-library'; child.kind = 'thread'; child.externalId = 'C1:123.001'; child.parentConversationId = 'slack-parent';
  state.conversations.push({ ...child, id: 'slack-parent', externalId: 'C1', kind: 'channel', parentConversationId: null }); state.messages.push({ ...message, id: 'slack-root', externalId: 'C1:123.001', conversationId: 'slack-parent', bodyText: 'Share your component examples in this thread.', bodyMarkdown: null, reactions: [] });
  await page.goto(`${app.base}/messages`); await page.getByRole('tab', { name: /Chat/ }).click(); await page.locator('[data-conversation-id="slack-parent"]').click(); await page.getByRole('button', { name: 'component-library 1 unread', exact: true }).click(); await expect(page.getByLabel('thumbsup, 3 reactions', { exact: true })).toBeVisible(); await expect(page.locator('pre code')).toContainText('const inbox'); await capture(page, info, 'p4', 'slack-thread');
  await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('```ts\nconst threadReply = true;\n```'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.locator('pre code').filter({ hasText: 'threadReply' })).toBeVisible(); expect((state.sent[0] as any).to.conversationId).toBe('conversation-chat'); await capture(page, info, 'p4', 'slack-replied');
});

test('new mail selects a discovered account and sends structured recipients', async ({ page }, info) => {
  await page.route('**/api/messages/outbox', async route => { state.sent.push(route.request().postDataJSON()); await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ item: { id: 'new-mail-outbox', status: 'held' } }) }); });
  await page.goto(`${app.base}/messages`); await page.getByRole('button', { name: 'Messages menu', exact: true }).click(); await page.getByRole('button', { name: 'New mail', exact: true }).click(); await page.getByRole('combobox', { name: 'From account', exact: true }).selectOption('google/work'); await page.getByRole('textbox', { name: 'To', exact: true }).fill('me@example.test'); await page.getByRole('textbox', { name: 'Cc', exact: true }).fill('colleague@example.test'); await page.getByRole('textbox', { name: 'Subject', exact: true }).fill('Weekly notes'); await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('The **weekly notes** are ready.'); await capture(page, info, 'p3', 'new-mail'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'New mail', exact: true })).toHaveCount(0); expect((state.sent[0] as any).to).toEqual({ address: 'me@example.test', cc: 'colleague@example.test', subject: 'Weekly notes' }); expect((state.sent[0] as any).account).toBe('work');
});
