import { test, expect } from '@playwright/test';
import type { Page, TestInfo } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { TalkApp } from '../fixtures/talk-app';
import { startTalkApp, freePort, scratchHome } from '../fixtures/talk-app';
import { seed, installFixtures } from './fixtures';
import type { FixtureState } from './fixtures';
let app: TalkApp; let state: FixtureState;
test.beforeAll(async () => { app = await startTalkApp({ home: scratchHome('messages-ship-ui-'), gatewayUrl: `http://127.0.0.1:${await freePort()}`, port: await freePort() }); await fetch(`${app.base}/messages`); });
test.afterAll(async () => { await app?.stop(); });
test.beforeEach(async ({ page }) => { state = seed(); await installFixtures(page, state); });
async function online(page: Page, value: boolean) { await page.evaluate(value => { Object.defineProperty(navigator, 'onLine', { configurable: true, get: () => value }); dispatchEvent(new Event(value ? 'online' : 'offline')); }, value); }
async function capture(page: Page, info: TestInfo, name: string) { await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && scrollY === 0)).toBe(true); if (info.project.name === 'iphone') await expect.poll(async () => (await page.locator('.app-bar').boundingBox())!.y).toBe(0); const folder = path.join(process.cwd(), 'evidence/messages/p8'); await fs.mkdir(folder, { recursive: true }); const file = path.join(folder, `${name}-${info.project.name}.png`); await page.screenshot({ path: file }); await info.attach(name, { path: file, contentType: 'image/png' }); }
test('offline state and sends persist as structured pending actions and replay once', async ({ page }, info) => { await page.goto(`${app.base}/messages`); await page.locator('[data-conversation-id="conversation-chat"]').click(); await expect.poll(() => state.messages.find(message => message.id === 'chat')!.read).toBe(true); await online(page, false); await page.getByRole('button', { name: 'Conversation menu', exact: true }).click(); await page.getByRole('button', { name: 'Mark unread', exact: true }).click(); await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('Queued while offline'); await page.getByRole('button', { name: 'Send message', exact: true }).click(); await expect(page.getByLabel('Conversation', { exact: true }).getByText('Queued while offline', { exact: true })).toBeVisible(); expect(state.sent).toHaveLength(0); await page.getByRole('button', { name: 'Conversation pending actions', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Pending actions', exact: true })).toContainText('Send message'); await expect(page.getByText('Message queued. It will send when connected.', { exact: true })).toHaveCount(0); await capture(page, info, 'offline-pending'); await page.getByRole('button', { name: 'Close pending', exact: true }).click(); await online(page, true); await expect.poll(() => state.sent.length).toBe(1); await expect.poll(() => state.messages.find(message => message.id === 'chat')!.read).toBe(false); await expect(page.getByRole('button', { name: 'Conversation pending actions', exact: true })).toHaveCount(0); await expect(page.getByLabel('Conversation', { exact: true }).getByText('Queued while offline', { exact: true })).toBeVisible(); await expect(page.getByText('Message queued. It will send when connected.', { exact: true })).toHaveCount(0); await capture(page, info, 'offline-replayed'); await online(page, true); expect(state.sent).toHaveLength(1); });

test('a thousand conversations redraw within 200ms and scroll without long frames', async ({ page }, info) => { const original = state.messages[4], conversation = state.conversations[4]; for (let i = 0; i < 1000; i++) { state.messages.push({ ...original, id: `perf-${i}`, conversationId: `perf-conv-${i}` }); state.conversations.push({ ...conversation, id: `perf-conv-${i}`, title: `Fixture ${i}` }); } await page.goto(`${app.base}/messages`); await expect(page.getByTestId('conversation-row').first()).toBeVisible(); const measurement = await page.evaluate(async () => { const row = document.querySelector('[data-testid="conversation-row"]')!; const list = row.parentElement!.parentElement!; const start = performance.now(); list.scrollTop = 44000; await new Promise(requestAnimationFrame); await new Promise(requestAnimationFrame); const redraw = performance.now() - start; const frames: number[] = []; let previous = performance.now(); for (let frame = 0; frame < 60; frame++) { list.scrollTop += 48; const now = await new Promise<number>(requestAnimationFrame); frames.push(now - previous); previous = now; } return { redraw, frames, rendered: document.querySelectorAll('[data-testid="conversation-row"]').length }; }); expect(measurement.redraw).toBeLessThan(200); expect(measurement.rendered).toBeLessThan(25); const steady = measurement.frames.slice(3).sort((a, b) => a - b); expect(steady[Math.floor(steady.length * .95)]).toBeLessThan(34); const folder = path.join(process.cwd(), 'evidence/messages/p8'); await fs.mkdir(folder, { recursive: true }); await fs.writeFile(path.join(folder, `performance-${info.project.name}.json`), JSON.stringify(measurement, null, 2)); await capture(page, info, 'performance-list'); });

test('composer remains visible when the phone viewport shrinks for the keyboard', async ({ page }, info) => { await page.goto(`${app.base}/messages/chat`); const input = page.getByRole('textbox', { name: 'Write a message', exact: true }); await input.fill('Reply while the keyboard is open'); if (info.project.name === 'iphone') await page.setViewportSize({ width: 390, height: 520 }); const bounds = await input.boundingBox(); expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height); await capture(page, info, 'keyboard-composer'); });

test('failed provider outbox item remains in the thread and Retry keeps a pending bubble', async ({ page }, info) => { state.outbox.push({ id: 'failed-send', provider: 'demo', account: 'fixture', to: { conversationId: 'conversation-chat' }, body: { markdown: 'Provider retry fixture' }, attachments: [], replyToExternalId: null, origin: 'user', holdUntil: new Date().toISOString(), status: 'failed', error: 'Provider is temporarily unavailable.' }); await page.goto(`${app.base}/messages/chat`); await expect(page.getByText('Provider retry fixture', { exact: true })).toBeVisible(); await expect(page.getByText('Provider is temporarily unavailable.', { exact: true })).toBeVisible(); await capture(page, info, 'failed-send'); await page.getByRole('button', { name: 'Could not send. Retry.', exact: true }).click(); await expect(page.getByText('Sending', { exact: true })).toBeVisible(); expect(state.outbox[0].status).toBe('held'); });
