#!/usr/bin/env bash
# Install (or repair) the DEV instance on this box. Idempotent — safe to re-run.
#
# Creates three things:
#   1. ~/.local/bin/garrison-dev-launch.sh   the launcher launchd executes
#   2. ~/Library/LaunchAgents/com.garrison.dev.plist   the on-demand unit
#   3. ~/.garrison-dev + ~/.claude-garrison-dev        dev's writable surfaces
#
# The unit is RunAtLoad=false / KeepAlive=false: dev must NOT come back by
# itself on boot or after a crash. Only prod (`com.garrison.jarvis`) is
# always-on. scripts/garrison-dev.sh drives this unit.
#
# Claude credentials are SYMLINKED, not copied, from the real ~/.claude — this
# box authenticates Claude Code from ~/.claude/.credentials.json (the login
# keychain is locked for headless agents), and a copy would silently go stale
# on the next token refresh. Everything else in dev's Claude home stays
# isolated, which is the part that matters.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_TREE="${GARRISON_DEV_TREE:-$HOME/dev/agent-garrison-dev}"
DEV_HOME="$HOME/.garrison-dev"
DEV_CLAUDE_HOME="$HOME/.claude-garrison-dev"
LABEL="com.garrison.dev"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LAUNCHER="$HOME/.local/bin/garrison-dev-launch.sh"

say() { printf "[dev-install] %s\n" "$*"; }

[ -d "$DEV_TREE/.git" ] || { echo "[dev-install] dev tree missing at $DEV_TREE" >&2; exit 1; }

# --- 1. launcher ------------------------------------------------------------
mkdir -p "$HOME/.local/bin"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/zsh
# Garrison DEV launcher (managed by launchd: $LABEL). Generated by
# scripts/garrison-dev-install.sh — edit that script, not this file.
#
# Runs the dev instance profile: app 7777, gateway 4777, fittings 70xx,
# GARRISON_HOME=~/.garrison-dev, CLAUDE_CONFIG_DIR=~/.claude-garrison-dev.
# Serves \`next dev\` from the working tree, so an edit is live on save.
#
# Unlike prod's launcher this does NOT auto-up the operative: a dev boot must
# not put a second voice agent on the microphone. Use garrison-dev.sh up.
emulate -L zsh
[ -f "\$HOME/.zshenv" ] && source "\$HOME/.zshenv"
cd "$DEV_TREE" || exit 1
exec npm run dev
LAUNCHER_EOF
chmod +x "$LAUNCHER"
say "launcher -> $LAUNCHER"

# --- 2. LaunchAgent ---------------------------------------------------------
mkdir -p "$HOME/Library/LaunchAgents" "$DEV_HOME/logs"
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/zsh</string>
    <string>$LAUNCHER</string>
  </array>
  <key>WorkingDirectory</key><string>$DEV_TREE</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key><string>$HOME</string>
    <key>PATH</key><string>$HOME/.local/node/bin:$HOME/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key><false/>
  <key>KeepAlive</key><false/>
  <key>ProcessType</key><string>Background</string>
  <key>StandardOutPath</key><string>$DEV_HOME/logs/launchd-dev.out.log</string>
  <key>StandardErrorPath</key><string>$DEV_HOME/logs/launchd-dev.err.log</string>
</dict>
</plist>
PLIST_EOF
say "plist -> $PLIST"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
say "LaunchAgent $LABEL loaded (on-demand)"

# --- 3. dev's writable surfaces --------------------------------------------
mkdir -p "$DEV_HOME"/{logs,runs,automations,orchestrator,ui-fittings,view-state,npm-cache,sessions,kanban-loop}
mkdir -p "$DEV_CLAUDE_HOME"/{projects,sessions}

# Claude Code refuses to start into its TUI without these two keys — it drops
# into the "choose a text style" onboarding screen, which the gateway reports
# as `spawn-failed: waiting on a login/setup screen`. The CLI reads the config
# from the SIBLING of its home when CLAUDE_CONFIG_DIR is set, i.e.
# $CLAUDE_CONFIG_DIR/.claude.json — see the note in garrison-instance.sh.
CLAUDE_JSON="$DEV_CLAUDE_HOME/.claude.json"
if [ ! -f "$CLAUDE_JSON" ]; then
  node -e '
    const fs = require("fs");
    const src = process.argv[1], dst = process.argv[2];
    let base = {};
    try {
      const real = JSON.parse(fs.readFileSync(src, "utf8"));
      // Carry only the onboarding-gating keys; dev must not inherit prod projects.
      for (const k of ["theme", "hasCompletedOnboarding", "installMethod", "autoUpdates", "userID"]) {
        if (real[k] !== undefined) base[k] = real[k];
      }
    } catch {}
    base.hasCompletedOnboarding = true;
    if (!base.theme) base.theme = "dark";
    base.projects = {};
    fs.writeFileSync(dst, JSON.stringify(base, null, 2));
  ' "$HOME/.claude.json" "$CLAUDE_JSON"
  say "seeded $CLAUDE_JSON"
fi

# Credentials: symlink so a token refresh in prod is picked up by dev too.
if [ -f "$HOME/.claude/.credentials.json" ] && [ ! -e "$DEV_CLAUDE_HOME/.credentials.json" ]; then
  ln -sfn "$HOME/.claude/.credentials.json" "$DEV_CLAUDE_HOME/.credentials.json"
  say "linked Claude credentials into dev"
elif [ ! -f "$HOME/.claude/.credentials.json" ]; then
  say "WARNING: ~/.claude/.credentials.json missing — dev's operative will not be able to log in"
fi

say "done. Control dev with: bash scripts/garrison-dev.sh {start|stop|status|up|down}"
